# -*- coding: utf-8 -*-
"""Tier B: 미수록 인기 애니/만화 + Tier C: 기존 시리즈 보강."""

TIER_B = {
    # ==================================================================
    # 체인소맨 (Chainsaw Man)
    # ==================================================================
    "체인소맨": [
        ("덴지", "denji_(chainsaw_man)"),
        ("포치타", "pochita"),
        ("마키마", "makima_(chainsaw_man)"),
        ("파워", "power_(chainsaw_man)"),
        ("아키 하야카와", "hayakawa_aki"),
        ("히메노", "himeno_(chainsaw_man)"),
        ("코베니 히가시야마", "higashiyama_kobeni"),
        ("아라이 히로후미", "arai_hirofumi"),
        ("키시베", "kishibe_(chainsaw_man)"),
        ("쿠사노", "kusano_(chainsaw_man)"),
        ("프린시", "princi_(chainsaw_man)"),
        ("레제", "reze_(chainsaw_man)"),
        ("폭탄의 악마", "reze_(chainsaw_man)"),
        ("키가와 키스기", "quanxi"),
        ("쿠완시", "quanxi"),
        ("산타클로스", "santa_claus_(chainsaw_man)"),
        ("코스모", "cosmo_(chainsaw_man)"),
        ("아사 미타카", "mitaka_asa"),
        ("미타카 아사", "mitaka_asa"),
        ("요루", "yoru_(chainsaw_man)"),
        ("전쟁의 악마", "yoru_(chainsaw_man)"),
        ("나유타", "nayuta_(chainsaw_man)"),
        ("후미코 미후네", "fumiko_mifune"),
        ("바라타", "barem_bridge"),
        ("바렘 브리지", "barem_bridge"),
        ("기로", "ghoul_(chainsaw_man)"),
        ("유우코", "fami_(chainsaw_man)"),
        ("파미", "fami_(chainsaw_man)"),
        ("티볼리", "tolka_(chainsaw_man)"),
    ],

    # ==================================================================
    # 주술회전 (Jujutsu Kaisen)
    # ==================================================================
    "주술회전": [
        ("이타도리 유지", "itadori_yuuji"),
        ("후시구로 메구미", "fushiguro_megumi"),
        ("쿠기사키 노바라", "kugisaki_nobara"),
        ("고죠 사토루", "gojo_satoru"),
        ("나나미 켄토", "nanami_kento"),
        ("이에이리 쇼코", "ieiri_shoko"),
        ("야가 마사미치", "yaga_masamichi"),
        ("게토 스구루", "getou_suguru"),
        ("이노 타카마", "ino_takuma"),
        ("후시구로 토지", "fushiguro_touji"),
        ("후시구로 츠미키", "fushiguro_tsumiki"),
        ("이누마키 토게", "inumaki_toge"),
        ("판다", "panda_(jujutsu_kaisen)"),
        ("제닌 마키", "zenin_maki"),
        ("제닌 마이", "zenin_mai"),
        ("미와 카스미", "miwa_kasumi"),
        ("니시미야 모모", "nishimiya_momo"),
        ("토도 아오이", "todou_aoi"),
        ("카미오 마사미", "kamo_noritoshi"),
        ("카모 노리토시", "kamo_noritoshi"),
        ("메카마루", "mechamaru"),
        ("쿠로이 가에이", "muta_kokichi"),
        ("무타 코키치", "muta_kokichi"),
        ("최유준", "kasumi_miwa"),
        ("우츠미 요시노부", "utsumi_yoshinobu"),
        ("우라우메", "uraume_(jujutsu_kaisen)"),
        ("죠고", "jogo_(jujutsu_kaisen)"),
        ("하나미", "hanami_(jujutsu_kaisen)"),
        ("마히토", "mahito_(jujutsu_kaisen)"),
        ("다곤", "dagon_(jujutsu_kaisen)"),
        ("쥬조", "choso_(jujutsu_kaisen)"),
        ("초소", "choso_(jujutsu_kaisen)"),
        ("쿠로이 마이", "yuki_tsukumo"),
        ("츠쿠모 유키", "yuki_tsukumo"),
        ("호시노 아오이", "todou_aoi"),
        ("나오비토", "zenin_naobito"),
        ("제닌 나오비토", "zenin_naobito"),
        ("후시구로 토지", "fushiguro_touji"),
        ("스쿠나", "ryomen_sukuna"),
        ("료멘 스쿠나", "ryomen_sukuna"),
    ],

    # ==================================================================
    # 장송의 프리렌
    # ==================================================================
    "장송의 프리렌": [
        ("프리렌", "frieren"),
        ("페른", "fern_(sousou_no_frieren)"),
        ("슈타르크", "stark_(sousou_no_frieren)"),
        ("히멜", "himmel_(sousou_no_frieren)"),
        ("하이터", "heiter_(sousou_no_frieren)"),
        ("아이젠", "eisen_(sousou_no_frieren)"),
        ("제리에", "serie_(sousou_no_frieren)"),
        ("플람메", "flamme_(sousou_no_frieren)"),
        ("크라프트", "kraft_(sousou_no_frieren)"),
        ("덴켄", "denken_(sousou_no_frieren)"),
        ("라위네", "laufen_(sousou_no_frieren)"),
        ("라우펜", "laufen_(sousou_no_frieren)"),
        ("리히터", "richter_(sousou_no_frieren)"),
        ("우반", "ubel_(sousou_no_frieren)"),
        ("우벨", "ubel_(sousou_no_frieren)"),
        ("쿤", "kanne_(sousou_no_frieren)"),
        ("칸네", "kanne_(sousou_no_frieren)"),
        ("라비네", "lawine_(sousou_no_frieren)"),
        ("메토데", "methode_(sousou_no_frieren)"),
        ("에델", "edel_(sousou_no_frieren)"),
        ("진제", "sense_(sousou_no_frieren)"),
        ("센세", "sense_(sousou_no_frieren)"),
        ("리니에", "linie_(sousou_no_frieren)"),
        ("아우라", "aura_(sousou_no_frieren)"),
        ("리네르네", "lernen_(sousou_no_frieren)"),
        ("페른 (모험가)", "fern_(sousou_no_frieren)"),
        ("후간크", "macht_(sousou_no_frieren)"),
        ("막트", "macht_(sousou_no_frieren)"),
    ],

    # ==================================================================
    # 봇치 더 락!
    # ==================================================================
    "봇치 더 락!": [
        ("고토 히토리", "gotou_hitori"),
        ("이지치 니지카", "ijichi_nijika"),
        ("야마다 료", "yamada_ryou"),
        ("키타 이쿠요", "kita_ikuyo"),
        ("이지치 세이카", "ijichi_seika"),
        ("히로이 키쿠리", "hiroi_kikuri"),
        ("고토 토모키", "gotou_tomoki"),
        ("고토 후타리", "gotou_futari"),
        ("나카무라 시미", "nakamura_shima"),
    ],

    # ==================================================================
    # 5등분의 신부
    # ==================================================================
    "5등분의 신부": [
        ("나카노 이치카", "nakano_ichika"),
        ("나카노 니노", "nakano_nino"),
        ("나카노 미쿠", "nakano_miku"),
        ("나카노 요츠바", "nakano_yotsuba"),
        ("나카노 이츠키", "nakano_itsuki"),
        ("우에스기 후타로", "uesugi_fuutarou"),
        ("나카노 라이하", "nakano_raiha"),
        ("우에스기 라이하", "uesugi_raiha"),
        ("마루오 마사요시", "maruo_masayoshi"),
        ("나카노 자네에몬", "nakano_zeniemon"),
    ],

    # ==================================================================
    # 카구야 님은 고백받고 싶어
    # ==================================================================
    "카구야 님은 고백받고 싶어": [
        ("시노미야 카구야", "shinomiya_kaguya"),
        ("시로가네 미유키", "shirogane_miyuki"),
        ("후지와라 치카", "fujiwara_chika"),
        ("이시가미 유우", "ishigami_yuu"),
        ("이이노 미코", "iino_miko"),
        ("쿄코 오노데라", "kashiwagi_nagisa"),
        ("카시와기 나기사", "kashiwagi_nagisa"),
        ("마키 모에하", "maki_moeha"),
        ("타니구치 츠바메", "koyasu_tsubame"),
        ("코야스 츠바메", "koyasu_tsubame"),
        ("츠바메 코야스", "koyasu_tsubame"),
        ("츠바사", "kashiwagi_tsubasa"),
        ("카시와기 츠바사", "kashiwagi_tsubasa"),
        ("시로가네 오노", "shirogane_kei"),
        ("시로가네 케이", "shirogane_kei"),
        ("키노 카렌", "kino_karen"),
        ("히이라기 슈치인", "hayasaka_ai"),
        ("하야사카 아이", "hayasaka_ai"),
    ],

    # ==================================================================
    # 그 비스크 돌은 사랑을 한다 (마이 드레스 업 달링)
    # ==================================================================
    "마이 드레스 업 달링": [
        ("키타가와 마린", "kitagawa_marin"),
        ("고죠 와쿠와", "gojou_wakana"),
        ("이노이 사쥬나", "inui_sajuna"),
        ("이노이 시즈쿠", "inui_shinju"),
        ("고죠 카오루", "gojou_kaoru"),
        ("아카네", "amane_(sono_bisque_doll)"),
    ],

    # ==================================================================
    # 리코리스 리코일
    # ==================================================================
    "리코리스 리코일": [
        ("니시키기 치사토", "nishikigi_chisato"),
        ("이노우에 타키나", "inoue_takina"),
        ("나카하라 미즈키", "nakahara_mizuki"),
        ("쿠루미", "kurumi_(lycoris_recoil)"),
        ("미카", "mika_(lycoris_recoil)"),
        ("후키", "fuki_(lycoris_recoil)"),
        ("사쿠라 키리하라", "kirihara_sakura"),
        ("히가시야마 사쿠라", "higashiyama_sakura"),
        ("로보타", "robota_(lycoris_recoil)"),
        ("마지마", "majima_(lycoris_recoil)"),
        ("츠지 신지", "tsuji_shinji"),
    ],

    # ==================================================================
    # 토라도라!
    # ==================================================================
    "토라도라!": [
        ("아이사카 타이가", "aisaka_taiga"),
        ("타카스 류지", "takasu_ryuuji"),
        ("쿠시에다 미노리", "kushieda_minori"),
        ("카와시마 아미", "kawashima_ami"),
        ("키타무라 유사쿠", "kitamura_yuusaku"),
        ("스미레 카노", "kanou_sumire"),
        ("카노 스미레", "kanou_sumire"),
        ("타카스 야스코", "takasu_yasuko"),
        ("아이사카 야스코", "aisaka_yasuko"),
    ],

    # ==================================================================
    # 시원찮은 그녀를 위한 육성방법 (사에카노)
    # ==================================================================
    "사에카노": [
        ("카토 메구미", "kato_megumi"),
        ("카스미가오카 우타하", "kasumigaoka_utaha"),
        ("사와무라 스펜서 에리리", "sawamura_spencer_eriri"),
        ("효도 미치루", "hyoudou_michiru"),
        ("하시마 이즈미", "hashima_izumi"),
        ("아키 토모야", "aki_tomoya"),
    ],

    # ==================================================================
    # 도키도키 문예부
    # ==================================================================
    "도키도키 문예부": [
        ("모니카", "monika_(doki_doki_literature_club)"),
        ("사요리", "sayori_(doki_doki_literature_club)"),
        ("유리", "yuri_(doki_doki_literature_club)"),
        ("나츠키", "natsuki_(doki_doki_literature_club)"),
    ],

    # ==================================================================
    # 페르소나 시리즈 (Persona) — 3/4/5 중심
    # ==================================================================
    "페르소나 시리즈": [
        # Persona 3
        ("유우키 마코토", "yuuki_makoto_(persona_3)"),
        ("타키바 유카리", "takeba_yukari"),
        ("산다 아키히코", "sanada_akihiko"),
        ("이오리 준페이", "iori_junpei"),
        ("키리죠 미츠루", "kirijo_mitsuru"),
        ("아라가키 신지로", "aragaki_shinjirou"),
        ("아미다 후우카", "yamagishi_fuuka"),
        ("아이기스", "aigis_(persona)"),
        ("코로마루", "koromaru"),
        ("아마다 켄", "amada_ken"),
        ("아라가키 신지로", "aragaki_shinjirou"),
        ("토우도우 나오토", "shirogane_naoto"),
        # Persona 4
        ("나루카미 유우", "narukami_yuu"),
        ("사토나카 치에", "satonaka_chie"),
        ("아마기 유키코", "amagi_yukiko"),
        ("쿠지카와 리세", "kujikawa_rise"),
        ("탓츠미 카나미", "tatsumi_kanji"),
        ("탓츠미 칸지", "tatsumi_kanji"),
        ("하나무라 요스케", "hanamura_yousuke"),
        ("시로가네 나오토", "shirogane_naoto"),
        ("쿠마", "kuma_(persona_4)"),
        ("도쥬마 료타로", "doujima_ryotaro"),
        ("도쥬마 나나코", "doujima_nanako"),
        ("마리", "marie_(persona_4)"),
        # Persona 5
        ("아마미야 렌", "amamiya_ren"),
        ("키타가와 유스케", "kitagawa_yusuke"),
        ("타카마키 안", "takamaki_anne"),
        ("사카모토 류지", "sakamoto_ryuji"),
        ("니지마 마코토", "niijima_makoto"),
        ("사쿠라 후타바", "sakura_futaba"),
        ("오쿠무라 하루", "okumura_haru"),
        ("아케치 고로", "akechi_goro"),
        ("키타가와 유스케", "kitagawa_yusuke"),
        ("모르가나", "morgana_(persona_5)"),
        ("요시자와 카스미", "yoshizawa_kasumi"),
        ("니지마 사에", "niijima_sae"),
        ("사쿠라 소지로", "sakura_sojiro"),
        ("타케미 타에", "takemi_tae"),
        ("카와카미 사다요", "kawakami_sadayo"),
        ("히루타 이치코", "ohya_ichiko"),
        ("오야 이치코", "ohya_ichiko"),
    ],

    # ==================================================================
    # 죠죠의 기묘한 모험 — 보강
    # ==================================================================
    "죠죠의 기묘한 모험": [
        ("죠나단 죠스타", "jonathan_joestar"),
        ("죠셉 죠스타", "joseph_joestar"),
        ("쿠죠 죠타로", "kuujou_joutarou"),
        ("히가시카타 죠스케", "higashikata_josuke"),
        ("죠르노 죠바나", "giorno_giovanna"),
        ("쿠죠 죠린", "kuujou_jolyne"),
        ("죠스타 죠스케", "higashikata_josuke"),
        ("죠지로 죠스타", "george_joestar"),
        ("디오 브란도", "dio_brando"),
        ("디오", "dio_brando"),
        ("주조 칸지", "iggy_(jojo)"),
        ("이기", "iggy_(jojo)"),
        ("폴나레프", "jean_pierre_polnareff"),
        ("아브돌", "muhammad_avdol"),
        ("카쿄인 노리아키", "kakyoin_noriaki"),
        ("야하르호 슐트라하인", "diavolo_(jojo)"),
        ("디아볼로", "diavolo_(jojo)"),
        ("브차라티", "bruno_bucciarati"),
        ("브루노 부차라티", "bruno_bucciarati"),
        ("나란치아", "narancia_ghirga"),
        ("미스타", "guido_mista"),
        ("판나코타 푸고", "pannacotta_fugo"),
        ("아바키오", "leone_abbacchio"),
        ("트리시 우나", "trish_una"),
        ("죠르노", "giorno_giovanna"),
        ("죠일더우드", "weather_report"),
        ("웨더 리포트", "weather_report"),
        ("프 푸치", "enrico_pucci"),
        ("엔리코 푸치", "enrico_pucci"),
        ("야스호 히로세", "hirose_yasuho"),
        ("죠스케 (8부)", "higashikata_josuke_(jojolion)"),
        ("히가시카타 야스호", "hirose_yasuho"),
    ],

    # ==================================================================
    # K-On! (케이온!)
    # ==================================================================
    "K-On!": [
        ("히라사와 유이", "hirasawa_yui"),
        ("아키야마 미오", "akiyama_mio"),
        ("타이나카 리츠", "tainaka_ritsu"),
        ("코토부키 츠무기", "kotobuki_tsumugi"),
        ("나카노 아즈사", "nakano_azusa"),
        ("히라사와 우이", "hirasawa_ui"),
        ("스즈키 준", "suzuki_jun"),
        ("야마나카 사와코", "yamanaka_sawako"),
        ("마나베 노도카", "manabe_nodoka"),
    ],

    # ==================================================================
    # 럭키스타 (Lucky Star)
    # ==================================================================
    "럭키스타": [
        ("이즈미 코나타", "izumi_konata"),
        ("히이라기 카가미", "hiiragi_kagami"),
        ("히이라기 츠카사", "hiiragi_tsukasa"),
        ("타카라 미유키", "takara_miyuki"),
        ("코우바이타 야츠카", "kobayakawa_yutaka"),
        ("쿠로이 나노코", "kuroi_nanako"),
        ("이와사키 미나미", "iwasaki_minami"),
        ("나르사사 메구미", "narumi_yui"),
    ],

    # ==================================================================
    # 일상 (Nichijou)
    # ==================================================================
    "일상": [
        ("아이오이 유우코", "aioi_yuuko"),
        ("나가노하라 미오", "naganohara_mio"),
        ("미나카미 마이", "minakami_mai"),
        ("샤크슈크", "shakushaku"),
        ("시노노메 나노", "shinonome_nano"),
        ("하카세", "hakase_(nichijou)"),
        ("사카모토", "sakamoto_(nichijou)"),
        ("나카무라 마코토", "nakamura_makoto_(nichijou)"),
        ("사사키 히로토", "sasahara_kojiro"),
    ],

    # ==================================================================
    # 무직전생 (Mushoku Tensei)
    # ==================================================================
    "무직전생": [
        ("루데우스 그레이래트", "rudeus_greyrat"),
        ("실피에트", "sylphiette"),
        ("록시 미굴디아", "roxy_migurdia"),
        ("에리스 보레아스 그레이래트", "eris_boreas_greyrat"),
        ("올스테드", "orsted_(mushoku_tensei)"),
        ("히토가미", "hitogami_(mushoku_tensei)"),
        ("자놀바", "zanoba_shironu"),
        ("크리프 그라이몰", "cliff_grimoire"),
        ("아이샤 그레이래트", "aisha_greyrat"),
        ("노른 그레이래트", "norn_greyrat"),
        ("리리아 그레이래트", "lilia_greyrat"),
        ("라라 그레이래트", "lara_greyrat"),
        ("루시 그레이래트", "lucy_greyrat"),
        ("기레누 데돌디아", "ghyslaine_dedoldia"),
        ("나나호시 시즈카", "nanahoshi_shizuka"),
    ],

    # ==================================================================
    # 메이드 인 어비스
    # ==================================================================
    "메이드 인 어비스": [
        ("리코", "riko_(made_in_abyss)"),
        ("레그", "reg_(made_in_abyss)"),
        ("나나치", "nanachi_(made_in_abyss)"),
        ("미티", "mitty_(made_in_abyss)"),
        ("프루셰카", "prushka"),
        ("보 토두로크", "bondrewd"),
        ("본드루드", "bondrewd"),
        ("오제", "ozen"),
        ("리자", "lyza_(made_in_abyss)"),
        ("토르가", "torka_(made_in_abyss)"),
        ("쿠 코토", "faputa"),
        ("파푸타", "faputa"),
        ("벨라우", "vueko"),
        ("뷔에코", "vueko"),
        ("이리미", "irumyuui"),
    ],

    # ==================================================================
    # 단단단 (Dandadan)
    # ==================================================================
    "단단단": [
        ("모모 아야세", "ayase_momo"),
        ("오카루 켄", "ken_takakura_(dandadan)"),
        ("타카쿠라 켄", "ken_takakura_(dandadan)"),
        ("진 엔조지", "enjouji_jin"),
        ("아이라", "aira_shiratori"),
        ("시라토리 아이라", "aira_shiratori"),
        ("타로 카시", "kashima_taro"),
        ("키누타 아야", "kinta_sakata"),
        ("터보 할머니", "turbo_granny"),
        ("기 굠 옴", "okarun"),
        ("오카룬", "okarun"),
    ],
}

TIER_C = {
    # ==================================================================
    # 원피스 보강
    # ==================================================================
    "원피스": [
        ("니코 로빈", "nico_robin"),
        ("나미", "nami_(one_piece)"),
        ("페로나", "perona"),
        ("보아 한콕", "boa_hancock"),
        ("보아 산다소냐", "boa_sandersonia"),
        ("보아 마리골드", "boa_marigold"),
        ("타시기", "tashigi"),
        ("히나", "hina_(one_piece)"),
        ("스모커", "smoker_(one_piece)"),
        ("코비", "koby_(one_piece)"),
        ("바이올렛", "viola_(one_piece)"),
        ("레베카", "rebecca_(one_piece)"),
        ("샬롯 푸딩", "charlotte_pudding"),
        ("샬롯 카타쿠리", "charlotte_katakuri"),
        ("샬롯 크라카", "charlotte_cracker"),
        ("샬롯 페로스페로", "charlotte_perospero"),
        ("샬롯 스무지", "charlotte_smoothie"),
        ("샬롯 빅맘", "charlotte_linlin"),
        ("샬롯 링링", "charlotte_linlin"),
        ("샬롯 셰베", "charlotte_chiffon"),
        ("샬롯 시폰", "charlotte_chiffon"),
        ("샬롯 라이라", "charlotte_galette"),
        ("야마토", "yamato_(one_piece)"),
        ("코우즈키 히요리", "kozuki_hiyori"),
        ("오뎀", "kozuki_oden"),
        ("코우즈키 오뎀", "kozuki_oden"),
        ("코우즈키 모모노스케", "kozuki_momonosuke"),
        ("코우즈키 토키", "kozuki_toki"),
        ("키쿠노죠", "kikunojo"),
        ("키쿠", "kikunojo"),
        ("이조", "izou_(one_piece)"),
        ("카리푸", "carrot_(one_piece)"),
        ("캐럿", "carrot_(one_piece)"),
        ("우타", "uta_(one_piece)"),
        ("샹크스", "shanks"),
        ("미호크", "dracule_mihawk"),
        ("드라큘 미호크", "dracule_mihawk"),
        ("이매진", "imu_(one_piece)"),
        ("이무", "imu_(one_piece)"),
        ("토라발가", "vegapunk_lilith"),
        ("리리스", "vegapunk_lilith"),
        ("아토라스", "vegapunk_atlas"),
        ("샤카", "vegapunk_shaka"),
        ("푸시", "vegapunk_pythagoras"),
        ("야크", "vegapunk_york"),
        ("요크", "vegapunk_york"),
        ("이도 가발리", "edward_newgate"),
    ],

    # ==================================================================
    # 나루토 보강
    # ==================================================================
    "나루토": [
        ("우즈마키 나루토", "uzumaki_naruto"),
        ("우치하 사스케", "uchiha_sasuke"),
        ("하루노 사쿠라", "haruno_sakura"),
        ("하타케 카카시", "hatake_kakashi"),
        ("히나타 휴우가", "hyuuga_hinata"),
        ("야마나카 이노", "yamanaka_ino"),
        ("아키미치 쵸지", "akimichi_chouji"),
        ("나라 시카마루", "nara_shikamaru"),
        ("이누즈카 키바", "inuzuka_kiba"),
        ("아부라메 시노", "aburame_shino"),
        ("템마리", "temari"),
        ("칸쿠로", "kankurou"),
        ("가아라", "gaara"),
        ("우치하 이타치", "uchiha_itachi"),
        ("우치하 마다라", "uchiha_madara"),
        ("오로치마루", "orochimaru_(naruto)"),
        ("츠나데", "tsunade_(naruto)"),
        ("지라이야", "jiraiya_(naruto)"),
        ("시즈네", "shizune"),
        ("쿠시나 우즈마키", "uzumaki_kushina"),
        ("미나토 나미카제", "namikaze_minato"),
        ("우즈마키 보루토", "uzumaki_boruto"),
        ("우치하 사라다", "uchiha_sarada"),
        ("미츠키", "mitsuki_(naruto)"),
        ("하나비 휴우가", "hyuuga_hanabi"),
        ("우치하 미코토", "uchiha_mikoto"),
        ("우치하 이즈미", "uchiha_izumi"),
        ("우즈마키 히마와리", "uzumaki_himawari"),
        ("코노한 우자키", "konan_(naruto)"),
        ("코난", "konan_(naruto)"),
        ("나가토", "nagato_(naruto)"),
        ("페인", "pain_(naruto)"),
        ("히단", "hidan_(naruto)"),
        ("카쿠즈", "kakuzu_(naruto)"),
        ("사소리", "sasori_(naruto)"),
        ("데이다라", "deidara_(naruto)"),
        ("키사메", "hoshigaki_kisame"),
        ("코지", "tobi_(naruto)"),
        ("토비", "tobi_(naruto)"),
    ],

    # ==================================================================
    # 블리치 보강
    # ==================================================================
    "블리치": [
        ("쿠로사키 이치고", "kurosaki_ichigo"),
        ("쿠치키 루키아", "kuchiki_rukia"),
        ("이노우에 오리히메", "inoue_orihime"),
        ("아바라이 렌지", "abarai_renji"),
        ("쿠로사키 카린", "kurosaki_karin"),
        ("쿠로사키 유즈", "kurosaki_yuzu"),
        ("마츠모토 란기쿠", "matsumoto_rangiku"),
        ("히츠가야 토시로", "hitsugaya_toushirou"),
        ("쿠로츠치 네무", "kurotsuchi_nemu"),
        ("쿠로츠치 마유리", "kurotsuchi_mayuri"),
        ("우노하나 레츠", "unohana_retsu"),
        ("우라하라 키스케", "urahara_kisuke"),
        ("야마모토 겐류사이", "yamamoto_genryuusai"),
        ("쿄라쿠 슌스이", "kyouraku_shunsui"),
        ("우키타케 쥬시로", "ukitake_juushirou"),
        ("쿠치키 뱌쿠야", "kuchiki_byakuya"),
        ("자라키 켄파치", "zaraki_kenpachi"),
        ("쿠사지시 야치루", "kusajishi_yachiru"),
        ("쟈쿠루 마키히사", "yadoumaru_lisa"),
        ("야도마루 리사", "yadoumaru_lisa"),
        ("히나모리 모모", "hinamori_momo"),
        ("코토에 키요네", "kotetsu_kiyone"),
        ("코토에 이세메", "kotetsu_isane"),
        ("코테츠 이세메", "kotetsu_isane"),
        ("이치마루 긴", "ichimaru_gin"),
        ("아이젠 소우스케", "aizen_sousuke"),
        ("토우센 카나메", "tousen_kaname"),
        ("울키오라 시퍼", "ulquiorra_cifer"),
        ("그림조 자거자크", "grimmjow_jaegerjaquez"),
        ("할리벨", "tia_harribel"),
        ("티아 할리벨", "tia_harribel"),
        ("아폴로", "apacci"),
        ("아파치", "apacci"),
        ("미라 로즈", "mila_rose"),
        ("선순", "sung-sun"),
    ],

    # ==================================================================
    # FGO (Fate/Grand Order) 보강 — 인기 서번트
    # ==================================================================
    "Fate/Grand Order": [
        ("마슈 키리에라이트", "mash_kyrielight"),
        ("나가타 시즈카", "fujimaru_ritsuka"),
        ("후지마루 리츠카", "fujimaru_ritsuka"),
        ("스카하", "scathach_(fate)"),
        ("스카사하 스카디", "scathach-skadi"),
        ("스카디", "scathach-skadi"),
        ("이리야스필 폰 아인츠베른", "illyasviel_von_einzbern"),
        ("쿠로 폰 아인츠베른", "chloe_von_einzbern"),
        ("아토라무 갈라테아", "atalanta_(fate)"),
        ("아탈란테", "atalanta_(fate)"),
        ("아스토르포", "astolfo_(fate)"),
        ("마리 앙투아네트", "marie_antoinette_(fate)"),
        ("샬롯 코르데", "charlotte_corday_(fate)"),
        ("앤 보니 & 메리 리드", "anne_bonny_(fate)"),
        ("이슈타르", "ishtar_(fate)"),
        ("에레슈키갈", "ereshkigal_(fate)"),
        ("스페이스 이슈타르", "space_ishtar"),
        ("토모에 고젠", "tomoe_gozen_(fate)"),
        ("미야모토 무사시", "miyamoto_musashi_(fate)"),
        ("진 잔다르크", "jeanne_d'arc_(fate)"),
        ("잔다르크 (얼터)", "jeanne_d'arc_alter"),
        ("잔다르크 알터", "jeanne_d'arc_alter"),
        ("잔 다르크 (산타 릴리)", "jeanne_d'arc_alter_santa_lily"),
        ("히로인 X", "heroine_x"),
        ("히로인 X 얼터", "heroine_x_alter"),
        ("히로인 XX", "heroine_xx"),
        ("주나", "junao"),
        ("멜트릴리스", "meltlilith"),
        ("패션 립", "passionlip"),
        ("BB (도쿄)", "bb_(fate)_(swimsuit_mooncancer)"),
        ("타마모 비스트", "tamamo_no_mae_(swimsuit_lancer)_(fate)"),
        ("타마모캐트", "tamamo_cat_(fate)"),
        ("타마모 노 마에", "tamamo_no_mae_(fate)"),
        ("아베노 세이메이", "abe_no_seimei"),
        ("쿠츠시카 호쿠사이", "katsushika_hokusai_(fate)"),
        ("오우즈쿠 호쿠사이", "katsushika_hokusai_(fate)"),
        ("우 즈키", "katsushika_oui"),
        ("페난드라 모건", "morgan_le_fay_(fate)"),
        ("모르간 르 페이", "morgan_le_fay_(fate)"),
        ("바트라잘", "bathory_(fate)"),
        ("엘리자베스 바토리", "elizabeth_bathory_(fate)"),
        ("모드레드", "mordred_(fate)"),
        ("아르토리아 펜드래곤 알터", "artoria_pendragon_(alter)"),
        ("아르토리아 페제로 알터", "artoria_pendragon_(lancer_alter)"),
        ("아르토리아 라이더 알터", "artoria_pendragon_(swimsuit_rider_alter)"),
        ("아르토리아 페그래곤", "artoria_pendragon_(fate)"),
        ("페그래", "altera_(fate)"),
        ("알테라", "altera_(fate)"),
        ("기네비어", "guinevere_(fate)"),
        ("니토크리스", "nitocris_(fate)"),
        ("페르세포네", "persephone_(fate)"),
        ("멜리시아 카운터", "melusine_(fate)"),
        ("멜뤼진", "melusine_(fate)"),
        ("순", "shuten_douji_(fate)"),
        ("슈텐도지", "shuten_douji_(fate)"),
        ("이바라키도지", "ibaraki_douji_(fate)"),
        ("미나모토노 라이코", "minamoto_no_raikou_(fate)"),
        ("코야스 츠바메", "okita_souji_(fate)"),
        ("오키타 소우지", "okita_souji_(fate)"),
        ("오키타 알터", "okita_souji_alter"),
        ("나가오카비카", "okita_souji_(swimsuit_saber)_(fate)"),
        ("후트", "fuuma_kotarou"),
        ("후우마 코타로", "fuuma_kotarou"),
        ("이즈모노 코토네", "izumo_no_okuni"),
        ("이즈모노 오쿠니", "izumo_no_okuni"),
        ("미네바 라오 자비", "minamoto_no_yoshitsune_(fate)"),
        ("미나모토노 요시츠네", "minamoto_no_yoshitsune_(fate)"),
        ("우시와카마루", "ushiwakamaru_(fate)"),
        ("벤케이", "musashibou_benkei_(fate)"),
        ("나가오 카게토라", "uesugi_kenshin_(fate)"),
        ("우에스기 켄신", "uesugi_kenshin_(fate)"),
        ("나가오 카게토라", "nagao_kagetora"),
    ],

    # ==================================================================
    # 나의 히어로 아카데미아 보강
    # ==================================================================
    "나의 히어로 아카데미아": [
        ("미도리야 이즈쿠", "midoriya_izuku"),
        ("바쿠고 카츠키", "bakugou_katsuki"),
        ("토도로키 쇼토", "todoroki_shouto"),
        ("이이다 텐야", "iida_tenya"),
        ("우라라카 오챠코", "uraraka_ochako"),
        ("야오요로즈 모모", "yaoyorozu_momo"),
        ("아스이 츠유", "asui_tsuyu"),
        ("쟈로", "jirou_kyouka"),
        ("지로 쿄카", "jirou_kyouka"),
        ("아시도 미나", "ashido_mina"),
        ("하구레 토오루", "hagakure_tooru"),
        ("키리시마 에지로", "kirishima_eijirou"),
        ("카미나리 덴키", "kaminari_denki"),
        ("세로 한타", "sero_hanta"),
        ("오지로 마시라오", "ojiro_mashirao"),
        ("토코야미 후미카게", "tokoyami_fumikage"),
        ("쇼지 메조", "shouji_mezou"),
        ("코다 코지", "kouda_kouji"),
        ("미네타 미노루", "mineta_minoru"),
        ("올 마이트", "all_might"),
        ("아이자와 쇼타", "aizawa_shouta"),
        ("미드나이트", "midnight_(boku_no_hero_academia)"),
        ("미츠키 카유", "miruko"),
        ("미루코", "miruko"),
        ("우사기야마 루미", "miruko"),
        ("핫스폼", "fat_gum"),
        ("코다 코우지", "kouda_kouji"),
        ("토가 히미코", "toga_himiko"),
        ("쇼토 토도로키", "todoroki_shouto"),
        ("토모로 시가라키", "shigaraki_tomura"),
        ("케키 치사키", "chisaki_kai"),
        ("치사키 카이", "chisaki_kai"),
        ("에리", "eri_(boku_no_hero_academia)"),
        ("멜리사 시일드", "melissa_shield"),
        ("아오야마 유가", "aoyama_yuuga"),
    ],

    # ==================================================================
    # 마블 코믹스 보강
    # ==================================================================
    "마블 코믹스": [
        ("나타샤 로마노프", "natasha_romanoff"),
        ("블랙 위도우", "black_widow_(marvel)"),
        ("완다 막시모프", "wanda_maximoff"),
        ("스칼렛 위치", "scarlet_witch"),
        ("캡틴 마블", "captain_marvel"),
        ("캐롤 댄버스", "carol_danvers"),
        ("진 그레이", "jean_grey"),
        ("스톰", "storm_(marvel)"),
        ("키티 프라이드", "kitty_pryde"),
        ("엠마 프로스트", "emma_frost"),
        ("새티르 만", "psylocke"),
        ("사이로크", "psylocke"),
        ("미즈 마블", "ms._marvel"),
        ("카말라 칸", "kamala_khan"),
        ("스파이더-그웬", "spider-gwen"),
        ("실크", "silk_(marvel)"),
        ("시디 문", "moon_girl"),
        ("매리 제인 왓슨", "mary_jane_watson"),
        ("그웬돌린 스테이시", "gwen_stacy"),
        ("페리스 햄튼", "felicia_hardy"),
        ("블랙 캣", "black_cat_(marvel)"),
        ("토르 (제인 포스터)", "thor_(jane_foster)"),
        ("발키리", "valkyrie_(marvel)"),
        ("아라크네", "spider-woman"),
        ("제시카 드류", "spider-woman"),
        ("도미노", "domino_(marvel)"),
        ("데드풀", "deadpool"),
        ("X-23", "x-23"),
        ("로라 키니", "x-23"),
        ("미스틱", "mystique_(marvel)"),
        ("재키 양", "she-hulk"),
        ("쉬헐크", "she-hulk"),
    ],

    # ==================================================================
    # DC 코믹스 보강
    # ==================================================================
    "DC 코믹스": [
        ("다이애나 프린스", "diana_prince"),
        ("원더우먼", "wonder_woman"),
        ("셀리나 카일", "selina_kyle"),
        ("캣우먼", "catwoman"),
        ("바버라 고든", "barbara_gordon"),
        ("배트걸", "batgirl"),
        ("스테파니 브라운", "stephanie_brown"),
        ("카산드라 케인", "cassandra_cain"),
        ("할리 퀸", "harley_quinn"),
        ("포이즌 아이비", "poison_ivy_(dc)"),
        ("파멜라 아이슬리", "poison_ivy_(dc)"),
        ("탈리아 알굴", "talia_al_ghul"),
        ("라스 알굴의 딸", "talia_al_ghul"),
        ("로이스 레인", "lois_lane"),
        ("스타파이어", "starfire_(dc)"),
        ("코랜드 안다스", "starfire_(dc)"),
        ("레이븐", "raven_(dc)"),
        ("팬텀 스트레인저", "phantom_stranger"),
        ("블랙 카나리", "black_canary"),
        ("다이나 랜스", "black_canary"),
        ("자타나", "zatanna_zatara"),
        ("파워걸", "power_girl"),
        ("슈퍼걸", "supergirl"),
        ("카라 조엘", "supergirl"),
        ("아쿠아맨", "aquaman"),
        ("머라", "mera_(dc)"),
        ("그린 애로우", "green_arrow"),
        ("플래시", "the_flash"),
        ("아이리스 웨스트", "iris_west"),
        ("월리 웨스트", "wally_west"),
        ("닉스 새비지", "nyssa_al_ghul"),
        ("니사 알굴", "nyssa_al_ghul"),
    ],

    # ==================================================================
    # 어떤 마술의 금서목록 / 과학의 초전자포 보강
    # ==================================================================
    "어떤 마술과학의 시리즈": [
        ("미사카 미코토", "misaka_mikoto"),
        ("시라이 쿠로코", "shirai_kuroko"),
        ("우이하루 카자리", "uiharu_kazari"),
        ("사텐 루이코", "saten_ruiko"),
        ("이마기노 후미카", "imagino_fumika"),
        ("미사카 이마기노", "imagino_fumika"),
        ("미코토 짜장면", "misaka_mikoto"),
        ("마이크 호크", "kongou_mitsuko"),
        ("콘고 미츠코", "kongou_mitsuko"),
        ("프로젝트 클론 미사카", "misaka_imouto"),
        ("미사카 이모우토", "misaka_imouto"),
        ("미사카 워스트", "misaka_worst"),
        ("미사카 마지카", "misaka_misuzu"),
        ("미사카 미즈리", "misaka_misuzu"),
        ("미사카 미스즈", "misaka_misuzu"),
        ("토오마", "kamijou_touma"),
        ("카미죠 토우마", "kamijou_touma"),
        ("인덱스", "index_(toaru_majutsu_no_index)"),
        ("스티유르 마글너스", "stiyl_magnus"),
        ("카오스 폼퍼티", "carissa_(toaru_majutsu_no_index)"),
        ("3등 공주 카리사", "carissa_(toaru_majutsu_no_index)"),
        ("히마와리 알리스", "alice_anotherbible"),
        ("아노더바이블 알리스", "alice_anotherbible"),
        ("이쿠 호우키쥬리", "fukiyose_seiri"),
        ("후키요세 세이리", "fukiyose_seiri"),
        ("리바리아 위그날", "lessar_(toaru_majutsu_no_index)"),
        ("레서", "lessar_(toaru_majutsu_no_index)"),
        ("프레메아 세이베른", "fremea_seivelun"),
        ("미사메", "fremea_seivelun"),
        ("악셀러레이터", "accelerator_(toaru_majutsu_no_index)"),
        ("미사카 9982", "misaka_9982"),
    ],

    # ==================================================================
    # 페어리테일 보강
    # ==================================================================
    "페어리테일": [
        ("에르자 스칼렛", "erza_scarlet"),
        ("나츠 드래그닐", "natsu_dragneel"),
        ("그레이 풀버스터", "gray_fullbuster"),
        ("쥬비아 록서", "juvia_lockser"),
        ("워든디아", "wendy_marvell"),
        ("웬디 마벨", "wendy_marvell"),
        ("미라쟌 스트라우스", "mirajane_strauss"),
        ("리잔나 스트라우스", "lisanna_strauss"),
        ("엘프만 스트라우스", "elfman_strauss"),
        ("칸나 알베로나", "cana_alberona"),
        ("락사스", "laxus_dreyar"),
        ("락사스 드레이어", "laxus_dreyar"),
        ("프리드 저스틴", "freed_justine"),
        ("에버그린", "evergreen_(fairy_tail)"),
        ("비키슬로", "bickslow"),
        ("가젤 레드폭스", "gajeel_redfox"),
    ],

    # ==================================================================
    # 단간론파 보강
    # ==================================================================
    "단간론파": [
        ("나에기 마코토", "naegi_makoto"),
        ("키리기리 쿄코", "kirigiri_kyouko"),
        ("후키가와 토우코", "fukawa_touko"),
        ("제노사이더 쇼우", "genocider_shou"),
        ("켈리 호카츠", "kelly_celes"),
        ("켈레스티아 류드엔벨크", "celestia_ludenberg"),
        ("코마에다 나기토", "komaeda_nagito"),
        ("히나타 하지메", "hinata_hajime"),
        ("츠미키 미키", "tsumiki_mikan"),
        ("소니아 네버민드", "sonia_nevermind"),
        ("핀크 마호", "saionji_hiyoko"),
        ("사이온지 히요코", "saionji_hiyoko"),
        ("쿠즈류 후유히코", "kuzuryuu_fuyuhiko"),
        ("페코야마 페코", "pekoyama_peko"),
        ("탕가루모", "tanaka_gundham"),
        ("탄아카 군햐쿠", "tanaka_gundham"),
        ("아키미 잇뽄마츠", "nidai_nekomaru"),
        ("니다이 네코마루", "nidai_nekomaru"),
        ("아오이 아사히나", "asahina_aoi"),
        ("오오와다 모운도", "oowada_mondo"),
        ("이시마루 키요타카", "ishimaru_kiyotaka"),
        ("산다이지 쿄스케", "munakata_kyousuke"),
        ("무나카타 쿄스케", "munakata_kyousuke"),
        ("키리기리 진", "kirigiri_jin"),
        ("샤일라 발케이리아", "shirogane_tsumugi"),
        ("시로가네 츠무기", "shirogane_tsumugi"),
        ("유메노 히미코", "yumeno_himiko"),
        ("아카마츠 카에데", "akamatsu_kaede"),
        ("하루카와 마키", "harukawa_maki"),
        ("토죠 키리미", "toujou_kirumi"),
        ("이루마 미우", "iruma_miu"),
        ("츄미노 양가", "yonaga_angie"),
        ("요나가 안지", "yonaga_angie"),
        ("초우노스케 시즈쿠", "chabashira_tenko"),
        ("차바시라 텐코", "chabashira_tenko"),
    ],

    # ==================================================================
    # 진격의 거인 보강
    # ==================================================================
    "진격의 거인": [
        ("미카사 아커만", "mikasa_ackerman"),
        ("아르민 알레르토", "armin_arlert"),
        ("에렌 예거", "eren_yeager"),
        ("크리스타 렌즈", "krista_lenz"),
        ("히스토리아 레이스", "historia_reiss"),
        ("이미르", "ymir_(shingeki_no_kyojin)"),
        ("히치 도리스", "hitch_dreyse"),
        ("아니 레온하트", "annie_leonhart"),
        ("페트라 랄", "petra_rall"),
        ("리바이", "levi_(shingeki_no_kyojin)"),
        ("에르빈 스미스", "erwin_smith"),
        ("한지 조에", "hange_zoe"),
        ("진네스 슈프링거", "sasha_blouse"),
        ("사샤 브라우스", "sasha_blouse"),
        ("코니 스프링거", "connie_springer"),
        ("장 키르슈타인", "jean_kirstein"),
        ("프록", "floch_forster"),
        ("플로크 포스터", "floch_forster"),
        ("피크 핑거", "pieck_finger"),
        ("가비 브라운", "gabi_braun"),
        ("팔코 그라이스", "falco_grice"),
    ],

    # ==================================================================
    # 귀멸의 칼날 보강
    # ==================================================================
    "귀멸의 칼날": [
        ("카마도 탄지로", "kamado_tanjirou"),
        ("카마도 네즈코", "kamado_nezuko"),
        ("아가츠마 젠이츠", "agatsuma_zenitsu"),
        ("하시비라 이노스케", "hashibira_inosuke"),
        ("츠유리 카나오", "tsuyuri_kanao"),
        ("코쵸 시노부", "kochou_shinobu"),
        ("코쵸 카나에", "kochou_kanae"),
        ("미츠리 칸로지", "kanroji_mitsuri"),
        ("토키토 무이치로", "tokitou_muichirou"),
        ("렌고쿠 쿄쥬로", "rengoku_kyoujurou"),
        ("우즈이 텐겐", "uzui_tengen"),
        ("렌고쿠 시즈에", "rengoku_shizue"),
        ("히메지마 교메이", "himejima_gyoumei"),
        ("이구로 오바나이", "iguro_obanai"),
        ("시나즈가와 산에미", "shinazugawa_sanemi"),
        ("토미오카 기유", "tomioka_giyuu"),
        ("츠바키", "tsubaki_(kimetsu_no_yaiba)"),
        ("키부츠지 무잔", "kibutsuji_muzan"),
        ("아카자", "akaza_(kimetsu_no_yaiba)"),
        ("도우마", "douma_(kimetsu_no_yaiba)"),
        ("쿠로사와 미시키", "shinobu_kochou"),
        ("쿠로사와 무이치로", "tokitou_muichirou"),
        ("우즈이 마키오", "uzui_makio"),
        ("우즈이 수마", "uzui_suma"),
        ("우즈이 히나츠루", "uzui_hinatsuru"),
        ("코쵸 카나에", "kochou_kanae"),
        ("아오이", "kanzaki_aoi"),
        ("칸자키 아오이", "kanzaki_aoi"),
        ("키요 카타라이", "nakahara_sumi"),
        ("나카하라 스미", "nakahara_sumi"),
    ],

    # ==================================================================
    # 원펀맨 보강
    # ==================================================================
    "원펀맨": [
        ("사이타마", "saitama_(one_punch_man)"),
        ("제노스", "genos"),
        ("타츠마키", "tatsumaki_(one_punch_man)"),
        ("후부키", "fubuki_(one_punch_man)"),
        ("바", "bang_(one_punch_man)"),
        ("뱅", "bang_(one_punch_man)"),
        ("실버 팡", "bang_(one_punch_man)"),
        ("아토믹 사무라이", "atomic_samurai"),
        ("킹", "king_(one_punch_man)"),
        ("메탈 나이트", "metal_knight"),
        ("어메이 컨", "amai_mask"),
        ("아마이 마스크", "amai_mask"),
        ("드라이브 나이트", "drive_knight"),
        ("픽 화이트", "pri-pri-prisoner"),
        ("프리프리프리즈너", "pri-pri-prisoner"),
        ("페란", "puri-puri_prisoner"),
        ("탱크탑 마스터", "tank_top_master"),
        ("실버판타스마", "silverfang"),
        ("스토츠 트라"),  # placeholder will skip
        ("플래쉬", "flashy_flash"),
        ("스피드 오 사운드 소닉", "speed-o'-sound_sonic"),
        ("페오리 ", "do-s_(one_punch_man)"),  # Already exists
    ],
}
# Clean up problematic entry
TIER_C["원펀맨"] = [t for t in TIER_C["원펀맨"] if isinstance(t, tuple) and len(t) == 2]
