# -*- coding: utf-8 -*-
"""Tier A: 메이저 미수록 시리즈 캐릭터 데이터.
영문 태그는 Danbooru/safebooru wiki에 등재된 공식 태그 표기를 사용한다.
한글명은 한국 정발/통용 표기 (호요버스/블아/우마무스메 등 정식 한국 서비스 기준).
"""

TIER_A = {
    # ==================================================================
    # 원신 (Genshin Impact) — 호요버스 한국 서비스 공식 한글명 기준
    # ==================================================================
    "원신": [
        ("아이테르", "aether_(genshin_impact)"),
        ("루미네", "lumine_(genshin_impact)"),
        ("페이몬", "paimon_(genshin_impact)"),
        # 몬드
        ("앰버", "amber_(genshin_impact)"),
        ("리사", "lisa_(genshin_impact)"),
        ("케이아", "kaeya_(genshin_impact)"),
        ("진", "jean_(genshin_impact)"),
        ("바바라", "barbara_(genshin_impact)"),
        ("다이루크", "diluc_(genshin_impact)"),
        ("디오나", "diona_(genshin_impact)"),
        ("벤티", "venti_(genshin_impact)"),
        ("레이저", "razor_(genshin_impact)"),
        ("피슬", "fischl_(genshin_impact)"),
        ("클레", "klee_(genshin_impact)"),
        ("모나", "mona_(genshin_impact)"),
        ("알베도", "albedo_(genshin_impact)"),
        ("로자리아", "rosaria_(genshin_impact)"),
        ("노엘", "noelle_(genshin_impact)"),
        ("벤넷", "bennett_(genshin_impact)"),
        ("에울라", "eula_(genshin_impact)"),
        ("미카", "mika_(genshin_impact)"),
        ("수크로스", "sucrose_(genshin_impact)"),
        # 리월
        ("종려", "zhongli_(genshin_impact)"),
        ("호두", "hu_tao_(genshin_impact)"),
        ("감우", "ganyu_(genshin_impact)"),
        ("응광", "ningguang_(genshin_impact)"),
        ("향릉", "xiangling_(genshin_impact)"),
        ("행추", "xingqiu_(genshin_impact)"),
        ("중운", "chongyun_(genshin_impact)"),
        ("북두", "beidou_(genshin_impact)"),
        ("각청", "keqing_(genshin_impact)"),
        ("신염", "xinyan_(genshin_impact)"),
        ("연비", "yanfei_(genshin_impact)"),
        ("소", "xiao_(genshin_impact)"),
        ("치치", "qiqi_(genshin_impact)"),
        ("타르탈리아", "tartaglia_(genshin_impact)"),
        ("야오야오", "yaoyao_(genshin_impact)"),
        ("운근", "yun_jin_(genshin_impact)"),
        ("야란", "yelan_(genshin_impact)"),
        ("신학", "shenhe_(genshin_impact)"),
        ("백출", "baizhu_(genshin_impact)"),
        ("가명", "gaming_(genshin_impact)"),
        ("치오리", "chiori_(genshin_impact)"),
        ("한운", "xianyun_(genshin_impact)"),
        ("람야", "lan_yan_(genshin_impact)"),
        # 이나즈마
        ("라이덴 쇼군", "raiden_shogun"),
        ("야에 미코", "yae_miko"),
        ("카미사토 아야카", "kamisato_ayaka"),
        ("카미사토 아야토", "kamisato_ayato"),
        ("아라타키 이토", "arataki_itto"),
        ("쿠죠 사라", "kujou_sara"),
        ("산고노미야 코코미", "sangonomiya_kokomi"),
        ("쿠키 시노부", "kuki_shinobu"),
        ("카에데하라 카즈하", "kaedehara_kazuha"),
        ("나가노하라 요이미야", "yoimiya_(genshin_impact)"),
        ("토마", "thoma_(genshin_impact)"),
        ("사유", "sayu_(genshin_impact)"),
        ("고로", "gorou_(genshin_impact)"),
        ("키라라", "kirara_(genshin_impact)"),
        ("시카노인 헤이조", "shikanoin_heizou"),
        ("유메미즈키 미즈키", "yumemizuki_mizuki"),
        # 수메르
        ("티나리", "tighnari_(genshin_impact)"),
        ("콜레이", "collei_(genshin_impact)"),
        ("도리", "dori_(genshin_impact)"),
        ("나히다", "nahida_(genshin_impact)"),
        ("니무", "nilou_(genshin_impact)"),
        ("사이노", "cyno_(genshin_impact)"),
        ("칸디스", "candace_(genshin_impact)"),
        ("레일라", "layla_(genshin_impact)"),
        ("알하이탐", "alhaitham_(genshin_impact)"),
        ("카베", "kaveh_(genshin_impact)"),
        ("데히야", "dehya_(genshin_impact)"),
        ("파루잔", "faruzan_(genshin_impact)"),
        ("방랑자", "wanderer_(genshin_impact)"),
        ("세토스", "sethos_(genshin_impact)"),
        # 폰타인
        ("리니", "lyney_(genshin_impact)"),
        ("리네트", "lynette_(genshin_impact)"),
        ("프레미네", "freminet_(genshin_impact)"),
        ("느비예트", "neuvillette_(genshin_impact)"),
        ("푸리나", "furina_(genshin_impact)"),
        ("샤를로트", "charlotte_(genshin_impact)"),
        ("나비아", "navia_(genshin_impact)"),
        ("슈브뢰즈", "chevreuse_(genshin_impact)"),
        ("클로린드", "clorinde_(genshin_impact)"),
        ("시그윈", "sigewinne_(genshin_impact)"),
        ("리오슬리", "wriothesley_(genshin_impact)"),
        ("아를레키노", "arlecchino_(genshin_impact)"),
        ("에밀리", "emilie_(genshin_impact)"),
        ("에스코피에", "escoffier_(genshin_impact)"),
        # 나타
        ("키니치", "kinich_(genshin_impact)"),
        ("무알라니", "mualani_(genshin_impact)"),
        ("샤스카", "chasca_(genshin_impact)"),
        ("카치나", "kachina_(genshin_impact)"),
        ("올로룬", "ororon_(genshin_impact)"),
        ("마비카", "mavuika_(genshin_impact)"),
        ("시틀랄리", "citlali_(genshin_impact)"),
        ("실로넨", "xilonen_(genshin_impact)"),
        ("이아샨", "iansan_(genshin_impact)"),
        ("바레사", "varesa_(genshin_impact)"),
        ("이파", "ifa_(genshin_impact)"),
        ("스커크", "skirk_(genshin_impact)"),
        ("달인", "dahlia_(genshin_impact)"),
        # 그 외
        ("일 도토레", "il_dottore_(genshin_impact)"),
        ("일 카피타노", "il_capitano_(genshin_impact)"),
        ("라 시뇨라", "la_signora_(genshin_impact)"),
        ("로사", "rosa_(genshin_impact)"),
        ("아로이", "aloy_(genshin_impact)"),
        ("다인슬레이프", "dainsleif_(genshin_impact)"),
    ],

    # ==================================================================
    # 붕괴: 스타레일 (Honkai: Star Rail)
    # ==================================================================
    "붕괴: 스타레일": [
        ("개척자", "trailblazer_(honkai:_star_rail)"),
        ("3월의 토끼", "march_7th_(honkai:_star_rail)"),
        ("단항", "dan_heng_(honkai:_star_rail)"),
        ("히메코", "himeko_(honkai:_star_rail)"),
        ("웰트", "welt_yang"),
        ("브로냐", "bronya_rand"),
        ("자라", "asta_(honkai:_star_rail)"),
        ("아스타", "asta_(honkai:_star_rail)"),
        ("페라", "pela_(honkai:_star_rail)"),
        ("자라", "serval_(honkai:_star_rail)"),
        ("서벌", "serval_(honkai:_star_rail)"),
        ("게파드", "gepard_(honkai:_star_rail)"),
        ("질리언", "gillian_(honkai:_star_rail)"),
        ("나타샤", "natasha_(honkai:_star_rail)"),
        ("샘포", "sampo_(honkai:_star_rail)"),
        ("후크", "hook_(honkai:_star_rail)"),
        ("제레", "seele_(honkai:_star_rail)"),
        ("미샤", "misha_(honkai:_star_rail)"),
        ("코코리아", "cocolia_(honkai:_star_rail)"),
        ("브리야", "bronya_rand"),
        ("백로", "bailu_(honkai:_star_rail)"),
        ("정운", "jing_yuan"),
        ("히메이", "qingque_(honkai:_star_rail)"),
        ("청작", "qingque_(honkai:_star_rail)"),
        ("청자", "tingyun_(honkai:_star_rail)"),
        ("정운", "jing_yuan"),
        ("스파클", "sparkle_(honkai:_star_rail)"),
        ("야오시", "yaoshi_(honkai:_star_rail)"),
        ("부동", "fu_xuan"),
        ("기염", "guinaifen"),
        ("연경", "yanqing_(honkai:_star_rail)"),
        ("정류운", "jingliu_(honkai:_star_rail)"),
        ("음월", "yinyue_(honkai:_star_rail)"),
        ("단심", "danshen_(honkai:_star_rail)"),
        ("연경", "yanqing_(honkai:_star_rail)"),
        ("음월", "yinyue_(honkai:_star_rail)"),
        ("월기", "yueqi_(honkai:_star_rail)"),
        ("판", "yukong_(honkai:_star_rail)"),
        ("위공", "yukong_(honkai:_star_rail)"),
        ("후오후오", "huohuo_(honkai:_star_rail)"),
        ("아건", "argenti_(honkai:_star_rail)"),
        ("로빈", "robin_(honkai:_star_rail)"),
        ("토파즈", "topaz_(honkai:_star_rail)"),
        ("카프카", "kafka_(honkai:_star_rail)"),
        ("실버울프", "silver_wolf_(honkai:_star_rail)"),
        ("블레이드", "blade_(honkai:_star_rail)"),
        ("저우즈", "guinaifen_(honkai:_star_rail)"),
        ("스월호닉", "sushang_(honkai:_star_rail)"),
        ("수상", "sushang_(honkai:_star_rail)"),
        ("화로", "luocha_(honkai:_star_rail)"),
        ("아벤츄린", "aventurine_(honkai:_star_rail)"),
        ("순", "sunday_(honkai:_star_rail)"),
        ("정실", "ruan_mei"),
        ("천성", "tianshu_(honkai:_star_rail)"),
        ("부효", "fu_xuan"),
        ("미스 푸", "fu_xuan"),
        ("미스터 큐", "mr._yang_(honkai:_star_rail)"),
        ("아샤", "asha_(honkai:_star_rail)"),
        ("아글라이아", "aglaea_(honkai:_star_rail)"),
        ("핑크스", "phainon_(honkai:_star_rail)"),
        ("파이논", "phainon_(honkai:_star_rail)"),
        ("미디우스", "mydei_(honkai:_star_rail)"),
        ("키프로스", "tribbie_(honkai:_star_rail)"),
        ("트리비", "tribbie_(honkai:_star_rail)"),
        ("히아킨토스", "hyacine_(honkai:_star_rail)"),
        ("히아신", "hyacine_(honkai:_star_rail)"),
        ("케스토스", "castorice_(honkai:_star_rail)"),
        ("카스토리스", "castorice_(honkai:_star_rail)"),
        ("아논", "anaxa_(honkai:_star_rail)"),
        ("아낙사", "anaxa_(honkai:_star_rail)"),
        ("센이", "saber_(honkai:_star_rail)"),
        ("싸이파", "cipher_(honkai:_star_rail)"),
        ("사이퍼", "cipher_(honkai:_star_rail)"),
    ],

    # ==================================================================
    # 붕괴 3rd (Honkai Impact 3rd)
    # ==================================================================
    "붕괴 3rd": [
        ("키아나 카슬라나", "kiana_kaslana"),
        ("라이덴 메이", "raiden_mei"),
        ("브로냐 자이치크", "bronya_zaychik"),
        ("후화", "fu_hua"),
        ("제레 폴레라이", "seele_vollerei"),
        ("테레사 아포칼립스", "theresa_apocalypse"),
        ("이리타", "rita_rossweisse"),
        ("리타 로스바이세", "rita_rossweisse"),
        ("히메코 무라타", "murata_himeko"),
        ("듀란달", "durandal_(honkai_impact)"),
        ("비안카", "bianka_ataegina"),
        ("리리야 켈리시야", "liliya_olenyeva"),
        ("로잘리", "rozaliya_olenyeva"),
        ("올레녜바", "rozaliya_olenyeva"),
        ("카리오레", "carole_peppers"),
        ("야에 사쿠라", "yae_sakura_(honkai_impact)"),
        ("야에 리세", "yae_rin"),
        ("야에 린", "yae_rin"),
        ("아포뉘아", "aponia_(honkai_impact)"),
        ("앨리스", "aurora_(honkai_impact)"),
        ("엘리시아", "elysia_(honkai_impact)"),
        ("패텐", "pardofelis_(honkai_impact)"),
        ("파르도펠리스", "pardofelis_(honkai_impact)"),
        ("그리세오", "griseo_(honkai_impact)"),
        ("그리시오", "griseo_(honkai_impact)"),
        ("사르돈", "sakura_yae_(honkai_impact)"),
        ("이오아네", "kalpas_(honkai_impact)"),
        ("케빈 카슬라나", "kevin_kaslana"),
        ("오토 아포칼립스", "otto_apocalypse"),
        ("프로메테우스", "prometheus_(honkai_impact)"),
        ("팀치", "timido_cute_(honkai_impact)"),
        ("코스미", "cosmis_(honkai_impact)"),
        ("코스마", "cosmis_(honkai_impact)"),
    ],

    # ==================================================================
    # 젠레스 존 제로 (Zenless Zone Zero)
    # ==================================================================
    "젠레스 존 제로": [
        ("벨", "belle_(zenless_zone_zero)"),
        ("와이즈", "wise_(zenless_zone_zero)"),
        ("불비", "bulbie_(zenless_zone_zero)"),
        ("앤비", "anby_demara"),
        ("니콜", "nicole_demara"),
        ("빌리", "billy_kid"),
        ("니코", "nekomata_(zenless_zone_zero)"),
        ("코린", "corin_wickes"),
        ("벤", "ben_bigger"),
        ("앤톤", "anton_ivanov_(zenless_zone_zero)"),
        ("소오카쿠", "soukaku_(zenless_zone_zero)"),
        ("엘렌", "ellen_joe"),
        ("리카온", "lycaon_(zenless_zone_zero)"),
        ("폰", "von_lycaon"),
        ("그레이스", "grace_howard"),
        ("코랄리온", "koleda_belobog"),
        ("코레다", "koleda_belobog"),
        ("라이칸", "lycaon_(zenless_zone_zero)"),
        ("리카온", "lycaon_(zenless_zone_zero)"),
        ("주", "zhu_yuan"),
        ("주위안", "zhu_yuan"),
        ("창", "qingyi_(zenless_zone_zero)"),
        ("칭이", "qingyi_(zenless_zone_zero)"),
        ("재인", "jane_doe_(zenless_zone_zero)"),
        ("진 도우", "jane_doe_(zenless_zone_zero)"),
        ("세스", "seth_lowell"),
        ("세스 라우월", "seth_lowell"),
        ("카에데하라", "caesar_king"),
        ("시저", "caesar_king"),
        ("부르닐드", "burnice_white"),
        ("번니스", "burnice_white"),
        ("리큐", "lighter_(zenless_zone_zero)"),
        ("라이터", "lighter_(zenless_zone_zero)"),
        ("미야비", "miyabi_hoshimi"),
        ("호시미 미야비", "miyabi_hoshimi"),
        ("야나기", "yanagi_(zenless_zone_zero)"),
        ("하루마사", "harumasa_(zenless_zone_zero)"),
        ("아오키 하루마사", "harumasa_(zenless_zone_zero)"),
        ("에비", "evelyn_chevalier"),
        ("이블린", "evelyn_chevalier"),
        ("아스트라", "astra_yao"),
        ("아스트라 야오", "astra_yao"),
        ("아냐", "anby_demara_(soldier_0)"),
        ("판", "pan_yinhu"),
        ("판인후", "pan_yinhu"),
        ("트리거", "trigger_(zenless_zone_zero)"),
        ("비비안", "vivian_banshee"),
        ("배쉬", "vivian_banshee"),
        ("히사기", "hugo_vlad"),
        ("휴고", "hugo_vlad"),
    ],

    # ==================================================================
    # 블루 아카이브 (Blue Archive) — 한국 정식 서비스 한글명
    # ==================================================================
    "블루 아카이브": [
        ("선생", "sensei_(blue_archive)"),
        # 아비도스
        ("호시노", "hoshino_(blue_archive)"),
        ("시로코", "shiroko_(blue_archive)"),
        ("아야네", "ayane_(blue_archive)"),
        ("세리카", "serika_(blue_archive)"),
        ("노아", "noa_(blue_archive)"),
        ("니노미야 시즈코", "shizuko_(blue_archive)"),
        # 게헨나
        ("아루", "aru_(blue_archive)"),
        ("무츠키", "mutsuki_(blue_archive)"),
        ("히후미", "hifumi_(blue_archive)"),
        ("하루카", "haruka_(blue_archive)"),
        ("이로하", "iroha_(blue_archive)"),
        ("카요코", "kayoko_(blue_archive)"),
        ("준코", "junko_(blue_archive)"),
        ("미치루", "michiru_(blue_archive)"),
        ("츠루기", "tsurugi_(blue_archive)"),
        ("이즈나", "izuna_(blue_archive)"),
        ("아카네", "akane_(blue_archive)"),
        ("호나미", "hanae_(blue_archive)"),
        ("하나에", "hanae_(blue_archive)"),
        ("후카", "fuuka_(blue_archive)"),
        ("히나", "hina_(blue_archive)"),
        ("이오리", "iori_(blue_archive)"),
        ("치아키", "chiaki_(blue_archive)"),
        ("아이리", "airi_(blue_archive)"),
        # 트리니티
        ("히마리", "himari_(blue_archive)"),
        ("히야마", "hiyori_(blue_archive)"),
        ("히요리", "hiyori_(blue_archive)"),
        ("나기사", "nagisa_(blue_archive)"),
        ("미카", "mika_(blue_archive)"),
        ("세이아", "seia_(blue_archive)"),
        ("히나타", "hinata_(blue_archive)"),
        ("코토리", "kotori_(blue_archive)"),
        ("사쿠라코", "sakurako_(blue_archive)"),
        ("스즈미", "suzumi_(blue_archive)"),
        ("코하루", "koharu_(blue_archive)"),
        ("츠바키", "tsubaki_(blue_archive)"),
        ("아즈사", "azusa_(blue_archive)"),
        ("미모리", "mimori_(blue_archive)"),
        ("히마와리", "himawari_(blue_archive)"),
        ("아리스", "aris_(blue_archive)"),
        ("미도리", "midori_(blue_archive)"),
        ("모모이", "momoi_(blue_archive)"),
        ("유즈", "yuzu_(blue_archive)"),
        ("네루", "neru_(blue_archive)"),
        ("아카리", "akari_(blue_archive)"),
        # 발키리
        ("준", "juri_(blue_archive)"),
        ("쥬리", "juri_(blue_archive)"),
        ("네루 알아", "neru_(blue_archive)"),
        ("키리노", "kirino_(blue_archive)"),
        # 미레니엄
        ("아스나", "asuna_(blue_archive)"),
        ("미사키", "misaki_(blue_archive)"),
        ("히마리", "himari_(blue_archive)"),
        ("코코나", "kokona_(blue_archive)"),
        ("토키", "toki_(blue_archive)"),
        ("니노", "nonomi_(blue_archive)"),
        ("노노미", "nonomi_(blue_archive)"),
        ("츠루기 미사키", "misaki_(blue_archive)"),
        ("우이", "ui_(blue_archive)"),
        ("우타하", "utaha_(blue_archive)"),
        ("아유미", "ayumi_(blue_archive)"),
        ("야쿠모", "yakumo_(blue_archive)"),
        ("나츠", "natsu_(blue_archive)"),
        ("쇼우코", "shouko_(blue_archive)"),
        ("리오", "rio_(blue_archive)"),
        ("히나리", "hinari_(blue_archive)"),
        ("미사카", "misa_(blue_archive)"),
        ("미사", "misa_(blue_archive)"),
        ("미야코", "miyako_(blue_archive)"),
        ("마키", "maki_(blue_archive)"),
        ("이로하", "iroha_(blue_archive)"),
        # 헬리오스
        ("미네", "mine_(blue_archive)"),
        ("쇼우코", "shouko_(blue_archive)"),
        # 산해경
        ("키사키", "kisaki_(blue_archive)"),
        ("렌게", "renge_(blue_archive)"),
        ("아카리", "akari_(blue_archive)"),
        ("키사키", "kisaki_(blue_archive)"),
        # 발할라
        ("이즈미", "izumi_(blue_archive)"),
        ("미나", "mina_(blue_archive)"),
        # SCHALE
        ("플랜", "plana_(blue_archive)"),
        ("플라나", "plana_(blue_archive)"),
        ("아로나", "arona_(blue_archive)"),
        ("에덴", "decalcomanie_(blue_archive)"),
        ("미카", "mika_(blue_archive)"),
        # 추가
        ("히마리", "himari_(blue_archive)"),
        ("츠루기", "tsurugi_(blue_archive)"),
        ("리오", "rio_(blue_archive)"),
        ("미카미", "mikamo_(blue_archive)"),
        ("히마리", "himari_(blue_archive)"),
        ("아카리", "akari_(blue_archive)"),
        ("히로", "hiro_(blue_archive)"),
        ("케이", "kei_(blue_archive)"),
        ("미사", "misa_(blue_archive)"),
        ("미아", "mia_(blue_archive)"),
        ("히유 사노", "sano_hiyori_(blue_archive)"),
        ("아카네 (밴드)", "akane_(band)_(blue_archive)"),
        ("히나 (수영복)", "hina_(swimsuit)_(blue_archive)"),
        ("아루 (드레스)", "aru_(dress)_(blue_archive)"),
        ("키사키 (게임웨어)", "kisaki_(gamewear)_(blue_archive)"),
        ("아스나 (밴드)", "asuna_(band)_(blue_archive)"),
        ("츠바키 (수영복)", "tsubaki_(swimsuit)_(blue_archive)"),
        ("호시노 (수영복)", "hoshino_(swimsuit)_(blue_archive)"),
        ("미카 (메이드)", "mika_(maid)_(blue_archive)"),
        ("아루 (신년)", "aru_(new_year)_(blue_archive)"),
        ("호시노 (배틀)", "hoshino_(battle)_(blue_archive)"),
        ("시로코 (사이버)", "shiroko_(cycling)_(blue_archive)"),
        ("히나 (드레스)", "hina_(dress)_(blue_archive)"),
        ("스미레", "sumire_(blue_archive)"),
        ("호우코", "horomi_(blue_archive)"),
        ("호로미", "horomi_(blue_archive)"),
        ("히메리", "himeri_(blue_archive)"),
        ("토모에", "tomoe_(blue_archive)"),
        ("코코미", "kokomi_(blue_archive)"),
        ("아유미", "ayumi_(blue_archive)"),
        ("키리노", "kirino_(blue_archive)"),
        ("미카게", "mikage_(blue_archive)"),
        ("나기사", "nagisa_(blue_archive)"),
        ("코토마", "kotama_(blue_archive)"),
        ("리코", "reisa_(blue_archive)"),
        ("레이사", "reisa_(blue_archive)"),
        ("미요", "miyu_(blue_archive)"),
        ("미유", "miyu_(blue_archive)"),
    ],

    # ==================================================================
    # 우마무스메 프리티 더비 (Umamusume)
    # ==================================================================
    "우마무스메 프리티 더비": [
        ("스페셜 위크", "special_week_(umamusume)"),
        ("사일런스 스즈카", "silence_suzuka_(umamusume)"),
        ("토카이 테이오", "tokai_teio_(umamusume)"),
        ("메지로 맥퀸", "mejiro_mcqueen_(umamusume)"),
        ("골드 십", "gold_ship_(umamusume)"),
        ("보드카", "vodka_(umamusume)"),
        ("다이와 스칼렛", "daiwa_scarlet_(umamusume)"),
        ("타이키 셔틀", "taiki_shuttle_(umamusume)"),
        ("그래스 원더", "grass_wonder_(umamusume)"),
        ("히시 아마존", "hishi_amazon_(umamusume)"),
        ("미호노 부르봉", "mihono_bourbon_(umamusume)"),
        ("멘솔리 메라쿠", "smart_falcon_(umamusume)"),
        ("스마트 팔콘", "smart_falcon_(umamusume)"),
        ("후지 키세키", "fuji_kiseki_(umamusume)"),
        ("오구리 캡", "oguri_cap_(umamusume)"),
        ("나리타 브라이언", "narita_brian_(umamusume)"),
        ("사쿠라 바쿠신 오", "sakura_bakushin_o_(umamusume)"),
        ("심볼리 루돌프", "symboli_rudolf_(umamusume)"),
        ("에어 그루브", "air_groove_(umamusume)"),
        ("아그네스 디지털", "agnes_digital_(umamusume)"),
        ("아그네스 타키온", "agnes_tachyon_(umamusume)"),
        ("세이운 스카이", "seiun_sky_(umamusume)"),
        ("토우카이 테이오", "tokai_teio_(umamusume)"),
        ("나리타 타이신", "narita_taishin_(umamusume)"),
        ("위닝 티켓", "winning_ticket_(umamusume)"),
        ("힘노가야 후미오", "fine_motion_(umamusume)"),
        ("파인 모션", "fine_motion_(umamusume)"),
        ("엘 콘도르 파사", "el_condor_pasa_(umamusume)"),
        ("토 카이 테이오", "tokai_teio_(umamusume)"),
        ("히시 아케보노", "hishi_akebono_(umamusume)"),
        ("마야노 톱건", "mayano_top_gun_(umamusume)"),
        ("매닉커 V", "manhattan_cafe_(umamusume)"),
        ("맨해튼 카페", "manhattan_cafe_(umamusume)"),
        ("미스터 시비", "mr._cb_(umamusume)"),
        ("이쿠노 딕터스", "ikuno_dictus_(umamusume)"),
        ("매트크리스 골드", "matikanetannhauser_(umamusume)"),
        ("매티카네 탄호이저", "matikanetannhauser_(umamusume)"),
        ("마티카네 탄호이저", "matikanetannhauser_(umamusume)"),
        ("스즈카 골드", "suzuka_gold_(umamusume)"),
        ("크리크 콜", "creek_paddock_(umamusume)"),
        ("사 사키 케이코", "sakura_chiyono_o_(umamusume)"),
        ("사쿠라 치요노 오", "sakura_chiyono_o_(umamusume)"),
        ("사쿠라 로렐", "sakura_laurel_(umamusume)"),
        ("츠루마루 츠요시", "tsurumaru_tsuyoshi_(umamusume)"),
        ("나카야마 페스타", "nakayama_festa_(umamusume)"),
        ("나리타 탑로드", "narita_top_road_(umamusume)"),
        ("아드미야 베가", "admire_vega_(umamusume)"),
        ("어드마이어 베가", "admire_vega_(umamusume)"),
        ("츠모 오토 토마토", "twin_turbo_(umamusume)"),
        ("트윈 터보", "twin_turbo_(umamusume)"),
        ("멘토르히메", "mejiro_dober_(umamusume)"),
        ("메지로 도벨", "mejiro_dober_(umamusume)"),
        ("메지로 라이언", "mejiro_ryan_(umamusume)"),
        ("메지로 파머", "mejiro_palmer_(umamusume)"),
        ("메지로 아르단", "mejiro_ardan_(umamusume)"),
        ("츠바키노 마더에", "biwa_hayahide_(umamusume)"),
        ("비와 하야히데", "biwa_hayahide_(umamusume)"),
        ("야에노 무테키", "yaeno_muteki_(umamusume)"),
        ("츠루기노 야에", "tsurugi_no_yaeno_(umamusume)"),
        ("키타산 블랙", "kitasan_black_(umamusume)"),
        ("사툰 다이아", "satono_diamond_(umamusume)"),
        ("사토노 다이아몬드", "satono_diamond_(umamusume)"),
        ("사토노 크라운", "satono_crown_(umamusume)"),
        ("듀란달", "duramente_(umamusume)"),
        ("듀라멘테", "duramente_(umamusume)"),
        ("쿠림손글로리", "curren_chan_(umamusume)"),
        ("쿠렌 짱", "curren_chan_(umamusume)"),
        ("코파노 리키", "copano_rickey_(umamusume)"),
        ("도토 코마쿠라", "do_tora_(umamusume)"),
        ("나리타 닉슨", "narita_top_road_(umamusume)"),
        ("심볼리 크리스 에스", "symboli_kris_s_(umamusume)"),
        ("나카야마 노 카타나", "nakayama_festa_(umamusume)"),
        ("미스터 C.B.", "mr._cb_(umamusume)"),
        ("리유 한자", "rice_shower_(umamusume)"),
        ("라이스 샤워", "rice_shower_(umamusume)"),
        ("히시 미라클", "hishi_miracle_(umamusume)"),
        ("탭 댄스 시티", "tap_dance_city_(umamusume)"),
        ("진다이 파오", "shinko_windy_(umamusume)"),
        ("신코 윈디", "shinko_windy_(umamusume)"),
        ("아드미야 그루브", "admire_groove_(umamusume)"),
        ("어드마이어 그루브", "admire_groove_(umamusume)"),
        ("힌델 베르크 옴마", "buena_vista_(umamusume)"),
        ("부에나비스타", "buena_vista_(umamusume)"),
        ("나리타 빈센트", "danon_premium_(umamusume)"),
        ("아오와스피아 럭키", "tama_modo_aozora_(umamusume)"),
    ],

    # ==================================================================
    # 명일방주 (Arknights)
    # ==================================================================
    "명일방주": [
        ("아미야", "amiya_(arknights)"),
        ("닥터", "doctor_(arknights)"),
        ("켈시", "kal'tsit_(arknights)"),
        ("카르틋", "kal'tsit_(arknights)"),
        ("텍사스", "texas_(arknights)"),
        ("엑시아", "exusiai_(arknights)"),
        ("크라운슬레이어", "crownslayer_(arknights)"),
        ("란 페가수스", "lappland_(arknights)"),
        ("라플란드", "lappland_(arknights)"),
        ("크로이아", "croissant_(arknights)"),
        ("크루아상", "croissant_(arknights)"),
        ("스카디", "skadi_(arknights)"),
        ("샤이닝", "shining_(arknights)"),
        ("나이팅게일", "nightingale_(arknights)"),
        ("이스트워드", "eyjafjalla_(arknights)"),
        ("에이야퍄들라", "eyjafjalla_(arknights)"),
        ("실버애시", "silverash_(arknights)"),
        ("스즈란", "suzuran_(arknights)"),
        ("시로", "siege_(arknights)"),
        ("시지", "siege_(arknights)"),
        ("호시구마", "hoshiguma_(arknights)"),
        ("샤마레", "shamare_(arknights)"),
        ("프로스트노바", "frostnova_(arknights)"),
        ("탈룰라", "talulah_(arknights)"),
        ("FrostLeaf", "frostleaf_(arknights)"),
        ("프로스트리프", "frostleaf_(arknights)"),
        ("리스카무", "liskarm_(arknights)"),
        ("프란카", "franka_(arknights)"),
        ("일강", "ifrit_(arknights)"),
        ("이프리트", "ifrit_(arknights)"),
        ("Saria", "saria_(arknights)"),
        ("사리아", "saria_(arknights)"),
        ("위슬래시", "whislash_(arknights)"),
        ("Sora", "sora_(arknights)"),
        ("소라", "sora_(arknights)"),
        ("Skadi the Corrupting Heart", "skadi_the_corrupting_heart"),
        ("Schwarz", "schwarz_(arknights)"),
        ("슈바르츠", "schwarz_(arknights)"),
        ("Surtr", "surtr_(arknights)"),
        ("슈르데", "surtr_(arknights)"),
        ("Mostima", "mostima_(arknights)"),
        ("모스티마", "mostima_(arknights)"),
        ("Mudrock", "mudrock_(arknights)"),
        ("머드록", "mudrock_(arknights)"),
        ("Magallan", "magallan_(arknights)"),
        ("마젤란", "magallan_(arknights)"),
        ("Specter", "specter_(arknights)"),
        ("스펙터", "specter_(arknights)"),
        ("Ch'en", "ch'en_(arknights)"),
        ("첸", "ch'en_(arknights)"),
        ("Hung", "hung_(arknights)"),
        ("훙", "hung_(arknights)"),
        ("Hellagur", "hellagur_(arknights)"),
        ("Phantom", "phantom_(arknights)"),
        ("팬텀", "phantom_(arknights)"),
        ("Bagpipe", "bagpipe_(arknights)"),
        ("백파이프", "bagpipe_(arknights)"),
        ("Blaze", "blaze_(arknights)"),
        ("블레이즈", "blaze_(arknights)"),
        ("W", "w_(arknights)"),
        ("Pinecone", "pinecone_(arknights)"),
        ("파인콘", "pinecone_(arknights)"),
        ("Andreana", "andreana_(arknights)"),
        ("안드레아나", "andreana_(arknights)"),
        ("Aak", "aak_(arknights)"),
        ("아크", "aak_(arknights)"),
        ("Beanstalk", "beanstalk_(arknights)"),
        ("Indra", "indra_(arknights)"),
        ("인드라", "indra_(arknights)"),
        ("Ptilopsis", "ptilopsis_(arknights)"),
        ("프티로프시스", "ptilopsis_(arknights)"),
        ("Warfarin", "warfarin_(arknights)"),
        ("와파린", "warfarin_(arknights)"),
        ("Ceylon", "ceylon_(arknights)"),
        ("세일론", "ceylon_(arknights)"),
        ("Skyfire", "skyfire_(arknights)"),
        ("스카이파이어", "skyfire_(arknights)"),
        ("GreyThroat", "greythroat_(arknights)"),
        ("그레이트로트", "greythroat_(arknights)"),
        ("Provence", "provence_(arknights)"),
        ("프로방스", "provence_(arknights)"),
        ("Platinum", "platinum_(arknights)"),
        ("플래티넘", "platinum_(arknights)"),
        ("Meteorite", "meteorite_(arknights)"),
        ("미티어라이트", "meteorite_(arknights)"),
        ("Vermeil", "vermeil_(arknights)"),
        ("Vermeil 베르메", "vermeil_(arknights)"),
        ("Beehunter", "beehunter_(arknights)"),
        ("벌사냥꾼", "beehunter_(arknights)"),
        ("Astgenne", "astgenne_(arknights)"),
        ("Roberta", "roberta_(arknights)"),
        ("Eunectes", "eunectes_(arknights)"),
        ("Highmore", "highmore_(arknights)"),
        ("Hibiscus", "hibiscus_(arknights)"),
        ("히비스커스", "hibiscus_(arknights)"),
        ("Folinic", "folinic_(arknights)"),
        ("Tomimi", "tomimi_(arknights)"),
        ("토미미", "tomimi_(arknights)"),
        ("Glaucus", "glaucus_(arknights)"),
        ("Bibeak", "bibeak_(arknights)"),
        ("Schwarz", "schwarz_(arknights)"),
        ("Greyy", "greyy_(arknights)"),
        ("Lava", "lava_(arknights)"),
        ("라바", "lava_(arknights)"),
        ("Steward", "steward_(arknights)"),
        ("Click", "click_(arknights)"),
        ("Catapult", "catapult_(arknights)"),
        ("Vigna", "vigna_(arknights)"),
        ("비냐", "vigna_(arknights)"),
        ("Cuora", "cuora_(arknights)"),
        ("Beagle", "beagle_(arknights)"),
        ("Spot", "spot_(arknights)"),
        ("Estelle", "estelle_(arknights)"),
        ("Matterhorn", "matterhorn_(arknights)"),
        ("Gummy", "gummy_(arknights)"),
        ("Vulcan", "vulcan_(arknights)"),
        ("발칸", "vulcan_(arknights)"),
        ("Asbestos", "asbestos_(arknights)"),
        ("Earthspirit", "earthspirit_(arknights)"),
        ("Cliffheart", "cliffheart_(arknights)"),
        ("Manticore", "manticore_(arknights)"),
        ("Reed", "reed_(arknights)"),
        ("리드", "reed_(arknights)"),
        ("Gravel", "gravel_(arknights)"),
        ("Jaye", "jaye_(arknights)"),
        ("Mayer", "mayer_(arknights)"),
        ("Conviction", "conviction_(arknights)"),
        ("Angelina", "angelina_(arknights)"),
        ("안젤리나", "angelina_(arknights)"),
        ("Nian", "nian_(arknights)"),
        ("니안", "nian_(arknights)"),
        ("Dusk", "dusk_(arknights)"),
        ("두스크", "dusk_(arknights)"),
        ("Ling", "ling_(arknights)"),
        ("Chongyue", "chongyue_(arknights)"),
        ("Shu", "shu_(arknights)"),
        ("Yato", "yato_(arknights)"),
        ("야토", "yato_(arknights)"),
        ("NoirCorne", "noir_corne_(arknights)"),
        ("Rangers", "rangers_(arknights)"),
        ("Cliffheart", "cliffheart_(arknights)"),
        ("Texas the Omertosa", "texas_the_omertosa"),
        ("Lappland the Decadenza", "lappland_the_decadenza"),
        ("Mizuki", "mizuki_(arknights)"),
        ("미즈키", "mizuki_(arknights)"),
        ("Lin", "lin_(arknights)"),
        ("La Pluma", "la_pluma_(arknights)"),
        ("Goldenglow", "goldenglow_(arknights)"),
        ("골든글로", "goldenglow_(arknights)"),
        ("Pallas", "pallas_(arknights)"),
        ("Mlynar", "mlynar_(arknights)"),
        ("Reed the Flame Shadow", "reed_the_flame_shadow"),
        ("Texas the Omertosa", "texas_the_omertosa"),
        ("Penance", "penance_(arknights)"),
    ],

    # ==================================================================
    # 동방 프로젝트 (Touhou Project)
    # ==================================================================
    "동방 프로젝트": [
        ("하쿠레이 레이무", "hakurei_reimu"),
        ("키리사메 마리사", "kirisame_marisa"),
        ("이자요이 사쿠야", "izayoi_sakuya"),
        ("레미리아 스칼렛", "remilia_scarlet"),
        ("플랑드르 스칼렛", "flandre_scarlet"),
        ("파츄리 널릿지", "patchouli_knowledge"),
        ("홍 메이링", "hong_meiling"),
        ("키사메 마리사", "kirisame_marisa"),
        ("앨리스 마가트로이드", "alice_margatroid"),
        ("사이교우지 유유코", "saigyouji_yuyuko"),
        ("야쿠모 유카리", "yakumo_yukari"),
        ("야쿠모 란", "yakumo_ran"),
        ("야쿠모 친", "chen_(touhou)"),
        ("첸", "chen_(touhou)"),
        ("콘파쿠 요우무", "konpaku_youmu"),
        ("후지와라노 모코우", "fujiwara_no_mokou"),
        ("이나바 텟위", "inaba_tewi"),
        ("레이센 우동게인 이나바", "reisen_udongein_inaba"),
        ("야고코로 에이린", "yagokoro_eirin"),
        ("호우라이산 카구야", "houraisan_kaguya"),
        ("케이네", "kamishirasawa_keine"),
        ("카미시라사와 케이네", "kamishirasawa_keine"),
        ("이비키 스이카", "ibuki_suika"),
        ("호시구마 유우기", "hoshiguma_yuugi"),
        ("아키 미나리코", "aki_minoriko"),
        ("아키 시즈하", "aki_shizuha"),
        ("리리 화이트", "lily_white"),
        ("미스티아 로렐라이", "mystia_lorelei"),
        ("루미아", "rumia"),
        ("다이요세이", "daiyousei"),
        ("치루노", "cirno"),
        ("키시 키사메", "kishin_sagume"),
        ("사군메", "kishin_sagume"),
        ("키신 사구메", "kishin_sagume"),
        ("키친 헤카티아 라피슬라줄리", "hecatia_lapislazuli"),
        ("헤카티아 라피스라줄리", "hecatia_lapislazuli"),
        ("이부키 스이카", "ibuki_suika"),
        ("토모에 메이메이", "wakasagihime"),
        ("와카사기 공주", "wakasagihime"),
        ("케이크우치 미사키", "tatara_kogasa"),
        ("타타라 코가사", "tatara_kogasa"),
        ("리리야 켈리시야", "rumia"),
        ("나에 나가에", "yatsuhashi_tsukumo"),
        ("츠쿠모 야츠하시", "yatsuhashi_tsukumo"),
        ("니토리 카와시로", "kawashiro_nitori"),
        ("모리야 스와코", "moriya_suwako"),
        ("야사카 카나코", "yasaka_kanako"),
        ("코치야 사나에", "kochiya_sanae"),
        ("이나바 카지", "tewi_inaba"),
        ("호우즈키 키스메", "hoozuki_kisume"),
        ("쿠로다니 야마메", "kurodani_yamame"),
        ("미즈하시 파르시", "mizuhashi_parsee"),
        ("키신 사가메", "kishin_sagume"),
        ("렌코 우사미", "usami_renko"),
        ("마에리베리 한", "maribel_hearn"),
        ("후타츠이와 마미조", "futatsuiwa_mamizou"),
        ("토라마루 쇼우", "toramaru_shou"),
        ("나즈린", "nazrin"),
        ("히지리 뱌쿠렌", "hijiri_byakuren"),
        ("쿠모이 이치린", "kumoi_ichirin"),
        ("운잔", "unzan"),
        ("후라와", "mononobe_no_futo"),
        ("모노노베노 후토", "mononobe_no_futo"),
        ("토요사토미미노 미코", "toyosatomimi_no_miko"),
        ("소가노 토지코", "soga_no_tojiko"),
        ("기 이지", "kasodani_kyouko"),
        ("카소다니 쿄우코", "kasodani_kyouko"),
        ("호리카와 라이코", "horikawa_raiko"),
        ("키진 세이자", "kijin_seija"),
        ("스쿠나 시노미야", "sukuna_shinmyoumaru"),
        ("스쿠나 신묘우마루", "sukuna_shinmyoumaru"),
        ("이마이즈미 카게로우", "imaizumi_kagerou"),
        ("쇼토쿠 미코", "toyosatomimi_no_miko"),
        ("키치 마사", "kicchou_yachie"),
        ("키쵸우 야치에", "kicchou_yachie"),
        ("요시카 미야코", "yoshika_miyako"),
        ("미야코 요시카", "miyako_yoshika"),
        ("오뉴라마", "kurokoma_saki"),
        ("쿠로코마 사키", "kurokoma_saki"),
        ("죠우토 우샤미", "joutougu_mayumi"),
        ("죠우토우구 마유미", "joutougu_mayumi"),
        ("니나미 야오로", "ushizaki_urumi"),
        ("우시자키 우루미", "ushizaki_urumi"),
        ("이부키 스이카", "ibuki_suika"),
        ("에타니티 라르바", "eternity_larva"),
        ("키샤 호우지로", "kishou_houjirou"),
        ("이즈노미 사구메", "kishin_sagume"),
        ("호시미야 케이키", "haniyasushin_keiki"),
        ("하니야스신 케이키", "haniyasushin_keiki"),
        ("쿠라카 야미", "kurokoma_saki"),
        ("히사미 요리히메", "watatsuki_no_yorihime"),
        ("와타츠키노 요리히메", "watatsuki_no_yorihime"),
        ("와타츠키노 토요히메", "watatsuki_no_toyohime"),
        ("레이센", "reisen_(touhou)"),
    ],

    # ==================================================================
    # 보컬로이드 (Vocaloid)
    # ==================================================================
    "보컬로이드": [
        ("하츠네 미쿠", "hatsune_miku"),
        ("카가미네 린", "kagamine_rin"),
        ("카가미네 렌", "kagamine_len"),
        ("메구리네 루카", "megurine_luka"),
        ("카이토", "kaito_(vocaloid)"),
        ("메이코", "meiko_(vocaloid)"),
        ("GUMI", "gumi_(vocaloid)"),
        ("구미", "gumi_(vocaloid)"),
        ("IA", "ia_(vocaloid)"),
        ("이아", "ia_(vocaloid)"),
        ("리리", "lily_(vocaloid)"),
        ("MAYU", "mayu_(vocaloid)"),
        ("후카세", "fukase_(vocaloid)"),
        ("VY1", "vy1"),
        ("VY2", "vy2"),
        ("야마하 미키", "miki_(vocaloid)"),
        ("미키", "miki_(vocaloid)"),
        ("CUL", "cul_(vocaloid)"),
        ("유즈키 유카리", "yuzuki_yukari"),
        ("크리프톤 미라이", "hatsune_miku"),
        ("세에", "see-u"),
        ("SeeU", "see-u"),
        ("SF-A2 미키", "miki_(vocaloid)"),
        ("VOCALOID 카가미네 미쿠오", "kagamine_mikuo"),
        ("미쿠오", "kagamine_mikuo"),
        ("아쿠노 다이진", "akuno_daijin"),
        ("아쿠노 무스메", "akuno_musume"),
        ("아쿠노 메이드", "akuno_meido"),
        ("츠루마키 마키", "tsurumaki_maki"),
        ("타카네 카나데", "takane_kanade"),
        ("뉴포라 워시", "neru_akita"),
        ("아키타 네루", "akita_neru"),
        ("야미네 렌리", "yamine_renri"),
        ("VFLOWER", "v_flower"),
        ("플라워", "v_flower"),
        ("코코네", "kokone_(vocaloid)"),
        ("타카하시 츠바사", "kokone_(vocaloid)"),
        ("OLIVER", "oliver_(vocaloid)"),
        ("올리버", "oliver_(vocaloid)"),
        ("SONIKA", "sonika_(vocaloid)"),
    ],

    # ==================================================================
    # 호로라이브 (Hololive Production) — 일본 멤버 중심
    # ==================================================================
    "호로라이브": [
        ("토키노 소라", "tokino_sora"),
        ("아자키 아이리", "azki_(hololive)"),
        ("로보코 산", "roboco_san"),
        ("사쿠라 미코", "sakura_miko"),
        ("호쇼 마린", "houshou_marine"),
        ("우사다 페코라", "usada_pekora"),
        ("우루하 루시아", "uruha_rushia"),
        ("시라카미 후부키", "shirakami_fubuki"),
        ("나츠이로 마츠리", "natsuiro_matsuri"),
        ("아카이 하아토", "akai_haato"),
        ("아쿠아 마린", "minato_aqua"),
        ("미나토 아쿠아", "minato_aqua"),
        ("유키하나 라미", "yukihana_lamy"),
        ("모모스즈 네네", "momosuzu_nene"),
        ("시시로 보탄", "shishiro_botan"),
        ("오마루 폴카", "omaru_polka"),
        ("히메모리 루나", "himemori_luna"),
        ("츠노마키 와타메", "tsunomaki_watame"),
        ("토코야미 토와", "tokoyami_towa"),
        ("아마네 카나타", "amane_kanata"),
        ("쿠레이지 올리", "kureiji_ollie"),
        ("아유노라이아 멜피사", "anya_melfissa"),
        ("아냐 멜피사", "anya_melfissa"),
        ("파블린 무흐친키", "pavolia_reine"),
        ("파볼리아 레이네", "pavolia_reine"),
        ("아이라니 이오피프틴", "airani_iofifteen"),
        ("아이라니 이오피프틴", "airani_iofifteen"),
        ("모나 모에나", "moona_hoshinova"),
        ("문아 호시노바", "moona_hoshinova"),
        ("리사 마리나", "risu_(hololive)"),
        ("아유나다", "ayunda_risu"),
        ("아유나다 리수", "ayunda_risu"),
        ("나키리 아얌메", "nakiri_ayame"),
        ("오오조라 스바루", "oozora_subaru"),
        ("코마치 시오", "murasaki_shion"),
        ("무라사키 시온", "murasaki_shion"),
        ("이누가미 코로네", "inugami_korone"),
        ("네코마타 오카유", "nekomata_okayu"),
        ("시라누이 플레어", "shiranui_flare"),
        ("시라누이 후레아", "shiranui_flare"),
        ("시라누이 후레아", "shiranui_flare"),
        ("호쇼 마린", "houshou_marine"),
        ("시로가네 노엘", "shirogane_noel"),
        ("모리 칼리오페", "mori_calliope"),
        ("타카나시 키아라", "takanashi_kiara"),
        ("니노마에 이나니스", "ninomae_ina'nis"),
        ("이나니스", "ninomae_ina'nis"),
        ("가우르 구라", "gawr_gura"),
        ("아멜리아 왓슨", "watson_amelia"),
        ("이로후스 모나", "iofi_(hololive)"),
        ("쿠로카미 후미오", "kuroakami_fubuki"),
        ("이로피프틴", "airani_iofifteen"),
        ("오마루 폴카", "omaru_polka"),
        ("라플라스 다크니스", "laplus_darknesss"),
        ("타카네 루이", "takane_lui"),
        ("하쿠이 코요리", "hakui_koyori"),
        ("사카마타 클로에", "sakamata_chloe"),
        ("카자마 이로하", "kazama_iroha"),
        ("이로하", "kazama_iroha"),
        ("이로후이 마노", "iofi"),
        ("쿠레이지 올리", "kureiji_ollie"),
        ("이라니 이오프 피프틴", "airani_iofifteen"),
        ("호로", "fuwawa_abyssgard"),
        ("후와와", "fuwawa_abyssgard"),
        ("모코코", "mococo_abyssgard"),
        ("바엘즈", "tsukumo_sana"),
        ("츠쿠모 사나", "tsukumo_sana"),
        ("세레스 파우나", "ceres_fauna"),
        ("나나시 무메이", "nanashi_mumei"),
        ("크로니", "ouro_kronii"),
        ("우로 크로니", "ouro_kronii"),
        ("바엘즈", "hakos_baelz"),
        ("하코스 바엘즈", "hakos_baelz"),
        ("이로하 카자마", "kazama_iroha"),
    ],

    # ==================================================================
    # 함대 컬렉션 (Kantai Collection / 칸코레)
    # ==================================================================
    "함대 컬렉션": [
        ("후부키", "fubuki_(kancolle)"),
        ("무라사메", "murasame_(kancolle)"),
        ("무라쿠모", "murakumo_(kancolle)"),
        ("아카기", "akagi_(kancolle)"),
        ("카가", "kaga_(kancolle)"),
        ("히류", "hiryuu_(kancolle)"),
        ("소류", "souryuu_(kancolle)"),
        ("쇼카쿠", "shoukaku_(kancolle)"),
        ("즈이카쿠", "zuikaku_(kancolle)"),
        ("호쇼", "houshou_(kancolle)"),
        ("류조", "ryuujou_(kancolle)"),
        ("운류", "unryuu_(kancolle)"),
        ("아마기", "amagi_(kancolle)"),
        ("카츠라기", "katsuragi_(kancolle)"),
        ("준요", "junyou_(kancolle)"),
        ("히요", "hiyou_(kancolle)"),
        ("타이호", "taihou_(kancolle)"),
        ("나가토", "nagato_(kancolle)"),
        ("무츠", "mutsu_(kancolle)"),
        ("야마토", "yamato_(kancolle)"),
        ("무사시", "musashi_(kancolle)"),
        ("나가라", "nagara_(kancolle)"),
        ("센다이", "sendai_(kancolle)"),
        ("아부쿠마", "abukuma_(kancolle)"),
        ("키누", "kinu_(kancolle)"),
        ("이스즈", "isuzu_(kancolle)"),
        ("나카", "naka_(kancolle)"),
        ("진츠", "jintsuu_(kancolle)"),
        ("유라", "yura_(kancolle)"),
        ("아이오이 코하루", "kashima_(kancolle)"),
        ("카시마", "kashima_(kancolle)"),
        ("카토리", "katori_(kancolle)"),
        ("아오바", "aoba_(kancolle)"),
        ("후루타카", "furutaka_(kancolle)"),
        ("카코", "kako_(kancolle)"),
        ("키누가사", "kinugasa_(kancolle)"),
        ("키누", "kinu_(kancolle)"),
        ("아카기", "akagi_(kancolle)"),
        ("아타고", "atago_(kancolle)"),
        ("타카오", "takao_(kancolle)"),
        ("마야", "maya_(kancolle)"),
        ("초카이", "choukai_(kancolle)"),
        ("묘코", "myoukou_(kancolle)"),
        ("나치", "nachi_(kancolle)"),
        ("아시가라", "ashigara_(kancolle)"),
        ("하구로", "haguro_(kancolle)"),
        ("토네", "tone_(kancolle)"),
        ("치쿠마", "chikuma_(kancolle)"),
        ("히부키", "hibiki_(kancolle)"),
        ("이카즈치", "ikazuchi_(kancolle)"),
        ("이나즈마", "inazuma_(kancolle)"),
        ("아카츠키", "akatsuki_(kancolle)"),
        ("후부키", "fubuki_(kancolle)"),
        ("시라유키", "shirayuki_(kancolle)"),
        ("하츠유키", "hatsuyuki_(kancolle)"),
        ("미유키", "miyuki_(kancolle)"),
        ("이소나미", "isonami_(kancolle)"),
        ("아야나미", "ayanami_(kancolle)"),
        ("시키나미", "shikinami_(kancolle)"),
        ("아키츠키", "akizuki_(kancolle)"),
        ("테루즈키", "teruzuki_(kancolle)"),
        ("스즈츠키", "suzutsuki_(kancolle)"),
        ("하츠즈키", "hatsuzuki_(kancolle)"),
        ("시마카제", "shimakaze_(kancolle)"),
        ("유우다치", "yuudachi_(kancolle)"),
        ("사미다레", "samidare_(kancolle)"),
        ("사사라네", "harusame_(kancolle)"),
        ("하루사메", "harusame_(kancolle)"),
        ("야마시오", "yamashio_maru_(kancolle)"),
        ("키소", "kiso_(kancolle)"),
        ("타마", "tama_(kancolle)"),
        ("키타카미", "kitakami_(kancolle)"),
        ("오이", "ooi_(kancolle)"),
        ("쿠마", "kuma_(kancolle)"),
        ("타츠타", "tatsuta_(kancolle)"),
        ("텐류", "tenryuu_(kancolle)"),
        ("코미", "kongou_(kancolle)"),
        ("콩고", "kongou_(kancolle)"),
        ("히에이", "hiei_(kancolle)"),
        ("키리시마", "kirishima_(kancolle)"),
        ("하루나", "haruna_(kancolle)"),
        ("이세", "ise_(kancolle)"),
        ("휴가", "hyuuga_(kancolle)"),
        ("후소", "fusou_(kancolle)"),
        ("야마시로", "yamashiro_(kancolle)"),
        ("미쿠마", "mikuma_(kancolle)"),
        ("스즈야", "suzuya_(kancolle)"),
        ("쿠마노", "kumano_(kancolle)"),
    ],

    # ==================================================================
    # 아즈렌 (Azur Lane)
    # ==================================================================
    "아즈렌": [
        ("엔터프라이즈", "enterprise_(azur_lane)"),
        ("호넷", "hornet_(azur_lane)"),
        ("렉싱턴", "lexington_(azur_lane)"),
        ("사라토가", "saratoga_(azur_lane)"),
        ("요크타운", "yorktown_(azur_lane)"),
        ("워스파이트", "warspite_(azur_lane)"),
        ("후드", "hood_(azur_lane)"),
        ("벨파스트", "belfast_(azur_lane)"),
        ("프린스 오브 웨일즈", "prince_of_wales_(azur_lane)"),
        ("일러스트리어스", "illustrious_(azur_lane)"),
        ("빅토리어스", "victorious_(azur_lane)"),
        ("포미더블", "formidable_(azur_lane)"),
        ("앤슨", "anson_(azur_lane)"),
        ("이글", "eagle_(azur_lane)"),
        ("듀크 오브 요크", "duke_of_york_(azur_lane)"),
        ("어드미럴 힙퍼", "admiral_hipper_(azur_lane)"),
        ("프린츠 오이겐", "prinz_eugen_(azur_lane)"),
        ("비스마르크", "bismarck_(azur_lane)"),
        ("티르피츠", "tirpitz_(azur_lane)"),
        ("U-47", "u-47_(azur_lane)"),
        ("U-81", "u-81_(azur_lane)"),
        ("U-110", "u-110_(azur_lane)"),
        ("U-556", "u-556_(azur_lane)"),
        ("그라프 체펠린", "graf_zeppelin_(azur_lane)"),
        ("아카기", "akagi_(azur_lane)"),
        ("카가", "kaga_(azur_lane)"),
        ("아카기 무스메", "akagi-chan_(azur_lane)"),
        ("카가 무스메", "kaga-chan_(azur_lane)"),
        ("쇼카쿠", "shoukaku_(azur_lane)"),
        ("즈이카쿠", "zuikaku_(azur_lane)"),
        ("나가토", "nagato_(azur_lane)"),
        ("무츠", "mutsu_(azur_lane)"),
        ("야마시로", "yamashiro_(azur_lane)"),
        ("후소", "fusou_(azur_lane)"),
        ("타카오", "takao_(azur_lane)"),
        ("아타고", "atago_(azur_lane)"),
        ("초카이", "choukai_(azur_lane)"),
        ("마야", "maya_(azur_lane)"),
        ("미코구로 미", "mikasa_(azur_lane)"),
        ("미카사", "mikasa_(azur_lane)"),
        ("아카츠키", "akatsuki_(azur_lane)"),
        ("히부키", "hibiki_(azur_lane)"),
        ("이카즈치", "ikazuchi_(azur_lane)"),
        ("이나즈마", "inazuma_(azur_lane)"),
        ("아야나미", "ayanami_(azur_lane)"),
        ("시키나미", "shikinami_(azur_lane)"),
        ("후부키", "fubuki_(azur_lane)"),
        ("시라유키", "shirayuki_(azur_lane)"),
        ("유우다치", "yuudachi_(azur_lane)"),
        ("시구레", "shigure_(azur_lane)"),
        ("무라사메", "murasame_(azur_lane)"),
        ("사미다레", "samidare_(azur_lane)"),
        ("쥬노", "juneau_(azur_lane)"),
        ("애틀랜타", "atlanta_(azur_lane)"),
        ("산디에고", "san_diego_(azur_lane)"),
        ("페닉스", "phoenix_(azur_lane)"),
        ("브룩클린", "brooklyn_(azur_lane)"),
        ("헬레나", "helena_(azur_lane)"),
        ("클리블랜드", "cleveland_(azur_lane)"),
        ("페놀라", "pensacola_(azur_lane)"),
        ("아스토리아", "astoria_(azur_lane)"),
        ("뉴올리언스", "new_orleans_(azur_lane)"),
        ("미네아폴리스", "minneapolis_(azur_lane)"),
        ("포틀랜드", "portland_(azur_lane)"),
        ("인디애나폴리스", "indianapolis_(azur_lane)"),
        ("위치타", "wichita_(azur_lane)"),
        ("볼티모어", "baltimore_(azur_lane)"),
        ("브레머튼", "bremerton_(azur_lane)"),
        ("앵커리지", "anchorage_(azur_lane)"),
        ("뉴저지", "new_jersey_(azur_lane)"),
        ("아이오와", "iowa_(azur_lane)"),
        ("워싱턴", "washington_(azur_lane)"),
        ("사우스다코타", "south_dakota_(azur_lane)"),
        ("매사추세츠", "massachusetts_(azur_lane)"),
        ("얼라스카", "alaska_(azur_lane)"),
        ("괌", "guam_(azur_lane)"),
        ("샹그릴라", "shangri-la_(azur_lane)"),
        ("센티놀", "centaur_(azur_lane)"),
        ("드레이크", "drake_(azur_lane)"),
        ("어드미럴 그라프 슈페", "admiral_graf_spee_(azur_lane)"),
        ("프리드리히 데어 그로세", "friedrich_der_grosse_(azur_lane)"),
    ],

    # ==================================================================
    # 러브 라이브! (Love Live! 시리즈 전체)
    # ==================================================================
    "러브 라이브!": [
        # μ's (뮤즈)
        ("코사카 호노카", "kousaka_honoka"),
        ("아야세 에리", "ayase_eli"),
        ("미나미 코토리", "minami_kotori"),
        ("소노다 우미", "sonoda_umi"),
        ("호시조라 린", "hoshizora_rin"),
        ("니시키노 마키", "nishikino_maki"),
        ("코이즈미 하나요", "koizumi_hanayo"),
        ("토죠 노조미", "toujou_nozomi"),
        ("야자와 니코", "yazawa_nico"),
        # Aqours
        ("타카미 치카", "takami_chika"),
        ("사쿠라우치 리코", "sakurauchi_riko"),
        ("마츠우라 카난", "matsuura_kanan"),
        ("쿠로사와 다이아", "kurosawa_dia"),
        ("와타나베 요우", "watanabe_you"),
        ("츠시마 요시코", "tsushima_yoshiko"),
        ("쿠니키다 하나마루", "kunikida_hanamaru"),
        ("오하라 마리", "ohara_mari"),
        ("쿠로사와 루비", "kurosawa_ruby"),
        # 니지가사키 학원 스쿨 아이돌 동호회
        ("우에하라 아유무", "uehara_ayumu"),
        ("나카스 카스미", "nakasu_kasumi"),
        ("오사카 시즈쿠", "osaka_shizuku"),
        ("아사카 카린", "asaka_karin"),
        ("미야시타 아이", "miyashita_ai"),
        ("코노에 카나타", "konoe_kanata"),
        ("코노에 카나타", "konoe_kanata"),
        ("엠마 베르데", "emma_verde"),
        ("텐노지 리나", "tennouji_rina"),
        ("미후네 시오리코", "mifune_shioriko"),
        ("야자와 미아", "yazawa_mia"),
        ("자크 시키나", "zhong_lanzhu"),
        ("종 란주", "zhong_lanzhu"),
        ("히이라기 시즈쿠", "hiiragi_shizuku"),
        ("히이라기 미아", "yazawa_mia"),
        # Liella!
        ("시부야 카논", "shibuya_kanon"),
        ("탕 케케", "tang_keke"),
        ("아라이 사쿠라코", "arashi_sakurako"),
        ("아라시 사쿠라코", "arashi_sakurako"),
        ("히이라기 메이", "hazuki_ren"),
        ("하즈키 렌", "hazuki_ren"),
        ("히이라기 메이", "heanna_sumire"),
        ("헤안나 스미레", "heanna_sumire"),
        ("오니즈카 나츠미", "onitsuka_natsumi"),
        ("우엘무리 메이", "wakana_shiki"),
        ("와카나 시키", "wakana_shiki"),
        ("히이라기 메이", "hiiragi_mei"),
        ("히라사와 사스키", "hirasawa_sasuki"),
        ("오니츠카 나츠미", "onitsuka_natsumi"),
        ("나츠미", "onitsuka_natsumi"),
        ("츠즈리 유네", "tsuzuri_yuune"),
    ],

    # ==================================================================
    # 아이돌마스터 (THE iDOLM@STER) — 주요 시리즈 메인 캐릭터
    # ==================================================================
    "아이돌마스터": [
        # 765 프로
        ("아마미 하루카", "amami_haruka"),
        ("키사라기 치하야", "kisaragi_chihaya"),
        ("호시이 미키", "hoshii_miki"),
        ("미나세 이오리", "minase_iori"),
        ("타카츠키 야요이", "takatsuki_yayoi"),
        ("아키즈키 리츠코", "akizuki_ritsuko"),
        ("미우라 아즈사", "miura_azusa"),
        ("아키즈키 키리시키", "akizuki_ritsuko"),
        ("키쿠치 마코토", "kikuchi_makoto"),
        ("후타미 아미", "futami_ami"),
        ("후타미 마미", "futami_mami"),
        ("가나하 히비키", "ganaha_hibiki"),
        ("호조 카렌", "shijou_takane"),
        ("시조 타카네", "shijou_takane"),
        # 신데렐라 걸즈 — 주요 캐릭터
        ("시마무라 우즈키", "shimamura_uzuki"),
        ("시부야 린", "shibuya_rin"),
        ("혼다 미오", "honda_mio"),
        ("쥬뉴 안즈", "futaba_anzu"),
        ("후타바 안즈", "futaba_anzu"),
        ("우즈키", "shimamura_uzuki"),
        ("쟈루타 노자", "ranko_kanzaki"),
        ("칸자키 란코", "kanzaki_ranko"),
        ("이가라시 카코", "igarashi_kyoko"),
        ("이가라시 쿄코", "igarashi_kyoko"),
        ("진구지 시즈카", "jougasaki_mika"),
        ("죠가사키 미카", "jougasaki_mika"),
        ("죠가사키 리카", "jougasaki_rika"),
        ("타카가키 카에데", "takagaki_kaede"),
        ("나카노 유카", "nakano_yuka"),
        ("키리에 히마와리", "anastasia_(idolmaster)"),
        ("아나스타시아", "anastasia_(idolmaster)"),
        ("림 유아", "rin"),
        ("아베 나나", "abe_nana"),
        ("미사키 사요코", "mizuki_seira"),
        ("미즈키 세이라", "mizuki_seira"),
        ("호조 카렌", "houjou_karen"),
        ("후지모토 리나", "fujimoto_rina"),
        ("아카기 미라이", "tachibana_arisu"),
        ("타치바나 아리스", "tachibana_arisu"),
        ("오오이시 이즈미", "ooishi_izumi"),
        ("쥬뉴 안즈", "morikubo_nono"),
        ("모리쿠보 노노", "morikubo_nono"),
        ("타카모리 아이코", "takamori_aiko"),
        ("미야모토 프레데리카", "miyamoto_frederica"),
        ("키리네", "shibuya_rin"),
        ("미와 안 안", "miwa_anan"),
        ("코바야가와 사에", "kobayakawa_sae"),
        # 밀리언 라이브 — 일부
        ("타나카 코토하", "tanaka_kotoha"),
        ("아이카와 치나츠", "aikawa_chinatsu"),
        ("키타카미 레이카", "kitakami_reika"),
        ("모가미 시즈카", "mogami_shizuka"),
        ("쇼지 츠바사", "shouji_tsubasa"),
        ("호시이 미키", "hoshii_miki"),
        ("토쿠가와 마츠리", "tokugawa_matsuri"),
        ("나노세 마츠리", "nanase_matsuri"),
        ("스즈키 토우", "suzuki_tou"),
        ("우즈키 카오리", "kishi_nagisa"),
        ("키시 나기사", "kishi_nagisa"),
        ("후키이 코토미", "fukuda_noriko"),
        # 샤이니컬러즈 (シャイニーカラーズ)
        ("호시카와 사라", "hoshikawa_sara"),
        ("게이 미츠루", "tsukimura_temari"),
        ("츠키무라 테마리", "tsukimura_temari"),
        ("후카자와 츠뮤기", "fukazawa_tsumugi"),
        ("히이라기 메이", "kuwayama_chiyuki"),
        ("쿠와야마 치유키", "kuwayama_chiyuki"),
        ("산도 사시히로", "sonoda_chiyoko"),
        ("소노다 치요코", "sonoda_chiyoko"),
        ("타치바나 메구미", "ichikawa_hinana"),
        ("이치카와 히나나", "ichikawa_hinana"),
        ("타카츠노 마노", "yukoku_kiriko"),
        ("유코쿠 키리코", "yukoku_kiriko"),
    ],

    # ==================================================================
    # 프린세스 커넥트! Re:Dive
    # ==================================================================
    "프린세스 커넥트!": [
        ("페코린느", "pecorine_(princess_connect!)"),
        ("코코로", "kokkoro_(princess_connect!)"),
        ("카오리", "kaori_(princess_connect!)"),
        ("키리코", "rino_(princess_connect!)"),
        ("리노", "rino_(princess_connect!)"),
        ("키리코", "tamaki_(princess_connect!)"),
        ("타마키", "tamaki_(princess_connect!)"),
        ("카루이", "karyl_(princess_connect!)"),
        ("카일", "karyl_(princess_connect!)"),
        ("유우키", "yuuki_(princess_connect!)"),
        ("주코", "suzume_(princess_connect!)"),
        ("스즈메", "suzume_(princess_connect!)"),
        ("미사키", "misaki_(princess_connect!)"),
        ("스즈나", "suzuna_(princess_connect!)"),
        ("아키노", "akino_(princess_connect!)"),
        ("히요리", "hiyori_(princess_connect!)"),
        ("코우메", "kuuka_(princess_connect!)"),
        ("키리에", "miyako_(princess_connect!)"),
        ("미야코", "miyako_(princess_connect!)"),
        ("미사토", "misato_(princess_connect!)"),
        ("히카리", "hikari_(princess_connect!)"),
        ("시오리", "shiori_(princess_connect!)"),
        ("히노", "rei_(princess_connect!)"),
        ("레이", "rei_(princess_connect!)"),
        ("매그너", "mahiru_(princess_connect!)"),
        ("마히루", "mahiru_(princess_connect!)"),
        ("스모모", "sumomo_(princess_connect!)"),
        ("란파", "ranfa_(princess_connect!)"),
        ("진가", "jiga_(princess_connect!)"),
        ("나나카", "nanaka_(princess_connect!)"),
        ("키리코", "ayane_(princess_connect!)"),
        ("아야네", "ayane_(princess_connect!)"),
        ("나츠메", "natsume_(princess_connect!)"),
        ("미츠키", "mitsuki_(princess_connect!)"),
        ("키리코", "homare_(princess_connect!)"),
        ("호마레", "homare_(princess_connect!)"),
        ("하츠네", "hatsune_(princess_connect!)"),
        ("이리야", "ilya_(princess_connect!)"),
        ("쥰", "jun_(princess_connect!)"),
        ("리마", "rima_(princess_connect!)"),
        ("모니카", "monika_(princess_connect!)"),
        ("크리스티나", "christina_(princess_connect!)"),
        ("아오이", "aoi_(princess_connect!)"),
        ("니논", "ninon_(princess_connect!)"),
        ("쥰", "junior_(princess_connect!)"),
        ("미사토", "misato_(princess_connect!)"),
        ("미사키", "misaki_(princess_connect!)"),
    ],

    # ==================================================================
    # 프로젝트 세카이 (Project Sekai)
    # ==================================================================
    "프로젝트 세카이": [
        ("호시노 이치카", "hoshino_ichika"),
        ("텐마 사키", "tenma_saki"),
        ("모치즈키 호나미", "mochizuki_honami"),
        ("히노모리 시호", "hinomori_shiho"),
        ("히노모리 시즈쿠", "hinomori_shizuku"),
        ("모모이 아이리", "momoi_airi"),
        ("키리타니 하루카", "kiritani_haruka"),
        ("아오야기 토우야", "aoyagi_touya"),
        ("텐마 츠카사", "tenma_tsukasa"),
        ("쿠사나기 네네", "kusanagi_nene"),
        ("카미시로 루이", "kamishiro_rui"),
        ("오토리 에무", "ootori_emu"),
        ("아즈사와 코하네", "azusawa_kohane"),
        ("시라이시 안", "shiraishi_an"),
        ("시노노메 아키토", "shinonome_akito"),
        ("아오야기 토우야", "aoyagi_touya"),
        ("아키야마 미즈키", "akiyama_mizuki"),
        ("아사히나 마후유", "asahina_mafuyu"),
        ("키리시아 츠가루", "yoisaki_kanade"),
        ("요이사키 카나데", "yoisaki_kanade"),
        ("시노노메 에나", "shinonome_ena"),
    ],

    # ==================================================================
    # Re:제로부터 시작하는 이세계 생활
    # ==================================================================
    "리제로": [
        ("나츠키 스바루", "natsuki_subaru"),
        ("에밀리아", "emilia_(re:zero)"),
        ("렘", "rem_(re:zero)"),
        ("람", "ram_(re:zero)"),
        ("베아트리스", "beatrice_(re:zero)"),
        ("로즈월 L. 메이저스", "roswaal_l._mathers"),
        ("팩", "puck_(re:zero)"),
        ("펠릭스 아가일", "felix_argyle"),
        ("페리스", "felix_argyle"),
        ("크루쉬 카스툴", "crusch_karsten"),
        ("아나스타시아 호신", "anastasia_hoshin"),
        ("프리실라 바리에르", "priscilla_barielle"),
        ("에키드나", "echidna_(re:zero)"),
        ("미네르바", "minerva_(re:zero)"),
        ("티폰", "typhon_(re:zero)"),
        ("다프네", "daphne_(re:zero)"),
        ("세크메트", "sekhmet_(re:zero)"),
        ("카밀라", "carmilla_(re:zero)"),
        ("페트라 레이트", "petra_leyte"),
        ("프레데리카 바움가르텐", "frederica_baumann"),
        ("엘자 그란히르테", "elsa_granhiert"),
        ("메일리 포트루트", "meili_portroute"),
        ("미미 펄밧시", "mimi_pearlbaton"),
        ("티비 펄밧시", "tivey_pearlbaton"),
        ("헤타로 펄밧시", "hetaro_pearlbaton"),
        ("리카드 웰킨", "ricardo_welkin"),
    ],

    # ==================================================================
    # 이 멋진 세계에 축복을! (코노스바)
    # ==================================================================
    "코노스바": [
        ("사토 카즈마", "satou_kazuma"),
        ("아쿠아", "aqua_(konosuba)"),
        ("메구밍", "megumin"),
        ("다크니스", "darkness_(konosuba)"),
        ("위즈", "wiz_(konosuba)"),
        ("윤윤", "yunyun_(konosuba)"),
        ("크리스", "chris_(konosuba)"),
        ("아이리스", "iris_(konosuba)"),
        ("코메코", "komekko"),
        ("미츠루기 쿄야", "mitsurugi_kyouya"),
        ("바닐라 토스", "vanir_(konosuba)"),
        ("바닐", "vanir_(konosuba)"),
        ("세시리", "cecily_(konosuba)"),
    ],

    # ==================================================================
    # 슈타인즈 게이트 (Steins;Gate)
    # ==================================================================
    "슈타인즈 게이트": [
        ("오카베 린타로", "okabe_rintarou"),
        ("마키세 크리스", "makise_kurisu"),
        ("시이나 마유리", "shiina_mayuri"),
        ("키류 모에카", "kiryuu_moeka"),
        ("아마네 스즈하", "amane_suzuha"),
        ("페이리스 냐냐", "faris_nyannyan"),
        ("페이리스 뉴냐냐", "faris_nyannyan"),
        ("하시다 이타루", "hashida_itaru"),
        ("우라시바라 루카", "urushibara_ruka"),
        ("아키하 룸미호", "akiha_rumiho"),
    ],

    # ==================================================================
    # 데이트 어 라이브
    # ==================================================================
    "데이트 어 라이브": [
        ("토비이치 오리가미", "tobiichi_origami"),
        ("토카", "tohka_yatogami"),
        ("야토가미 토카", "tohka_yatogami"),
        ("요시노", "yoshino_(date_a_live)"),
        ("쿠루미", "tokisaki_kurumi"),
        ("토키사키 쿠루미", "tokisaki_kurumi"),
        ("이자요이 미쿠", "izayoi_miku"),
        ("이자요이 미쿠", "miku_izayoi"),
        ("미쿠", "izayoi_miku"),
        ("야마이 카구야", "yamai_kaguya"),
        ("야마이 유즈루", "yamai_yuzuru"),
        ("호시미야 무쿠로", "hoshimiya_mukuro"),
        ("토비이치 마나", "tobiichi_mana"),
        ("나토라 오리가미", "tobiichi_origami"),
        ("나토라 오리가미", "natsumi_(date_a_live)"),
        ("나츠미", "natsumi_(date_a_live)"),
        ("호시미야 무쿠로", "hoshimiya_mukuro"),
        ("니아 혼조", "honjou_nia"),
        ("혼조 니아", "honjou_nia"),
        ("니베르콜", "nibelcole"),
        ("이츠카 코토리", "itsuka_kotori"),
        ("이츠카 시도", "itsuka_shidou"),
        ("토노마치 히로토", "tonomachi_hiroto"),
        ("무라사메 레이네", "murasame_reine"),
        ("쿠루미 토키사키", "tokisaki_kurumi"),
        ("니비카 후토", "nibelcole"),
    ],

    # ==================================================================
    # 마법소녀 마도카☆마기카
    # ==================================================================
    "마법소녀 마도카☆마기카": [
        ("카나메 마도카", "kaname_madoka"),
        ("아케미 호무라", "akemi_homura"),
        ("미키 사야카", "miki_sayaka"),
        ("토모에 마미", "tomoe_mami"),
        ("사쿠라 쿄코", "sakura_kyouko"),
        ("큐베", "kyubey"),
        ("나기사 모모에", "momoe_nagisa"),
        ("미사키 사나", "futaba_sana"),
        ("야치요 미루나", "tamaki_iroha"),
        ("타마키 이로하", "tamaki_iroha"),
        ("미키 사야카", "miki_sayaka"),
        ("미카즈키 카에데", "mikazuki_kaede"),
        ("토오야마 무이", "tooyama_mui"),
        ("히이라기 후타바", "hiiragi_futaba"),
        ("일위", "akemi_homura"),
        ("아오바 츠루노", "aoba_tsuruno"),
        ("야쿠모 미타마", "yakumo_mitama"),
    ],
}
