import type { Preset } from "./types";

export const PRESETS: Preset[] = [
  // ── 기존 8개 (한국어 필드) ──────────────────────────────────────────
  {
    id: "marvel-battle",
    title: "마블 영웅 대전",
    description: "아이언맨 vs 캡틴 아메리카, 뉴욕 하늘 위 서사적 전투",
    emoji: "⚡",
    prompt:
      "Iron Man and Captain America in an epic aerial battle over the New York City skyline, wide shot, dramatic cinematic lighting, action-packed, explosions and repulsor blasts, cinematic realism style",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "아이언맨과 캡틴 아메리카",
    action: "폭발과 리펄서 빔이 터지는 서사적인 공중 전투",
    setting: "뉴욕 시 스카이라인",
    cameraShot: "wide shot",
    lighting: "dramatic shadows",
    mood: "epic action-packed",
    visualStyle: "cinematic realism",
  },
  {
    id: "disney-adventure",
    title: "디즈니 모험",
    description: "미키 마우스와 친구들의 마법 숲 탐험",
    emoji: "🏰",
    prompt:
      "Mickey Mouse and his friends exploring an enchanted magical forest, playful whimsical mood, soft diffused lighting, medium shot, Disney animation style, vibrant colors",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "미키 마우스와 친구들",
    action: "마법에 걸린 신비로운 숲을 탐험하는",
    setting: "마법의 숲, 선명한 색감의 나무와 꽃들",
    cameraShot: "medium shot",
    lighting: "soft diffused",
    mood: "playful whimsical",
    visualStyle: "painterly artistic",
  },
  {
    id: "cute-hamster",
    title: "귀여운 햄스터",
    description: "거대한 주방을 탐험하는 작은 햄스터",
    emoji: "🐹",
    prompt:
      "Tiny hamster on an adventure through a giant kitchen, close-up tracking shot, soft bokeh background, warm cozy lighting, playful whimsical mood, cinematic realism",
    settings: { duration: 5, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "아주 작은 햄스터",
    action: "거대한 주방을 모험하는",
    setting: "따뜻한 빛이 가득한 거대한 주방",
    cameraShot: "close-up",
    lighting: "soft diffused",
    mood: "playful whimsical",
    visualStyle: "soft bokeh",
  },
  {
    id: "dragon-flight",
    title: "용의 비행",
    description: "눈 덮인 산 위를 날아다니는 장엄한 용",
    emoji: "🐉",
    prompt:
      "Majestic dragon soaring over snow-capped mountain peaks, wide aerial shot, dramatic cinematic shadows, epic action-packed mood, fantasy magical visual style, misty clouds",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "장엄한 용",
    action: "안개 구름 사이 눈 덮인 산봉우리를 박차며 날아오르는",
    setting: "눈 덮인 산봉우리들",
    cameraShot: "aerial bird's eye shot",
    lighting: "dramatic shadows",
    mood: "epic action-packed",
    visualStyle: "fantasy magical",
  },
  {
    id: "tokyo-rain",
    title: "도쿄 빗속 야경",
    description: "빗속 네온 도쿄 거리, 사이버펑크 분위기",
    emoji: "🌃",
    prompt:
      "Neon-lit Tokyo street in rain at night, tracking shot, cyberpunk neon lighting, mysterious tense atmosphere, cinematic realism, reflections on wet asphalt, puddles glowing with neon signs",
    settings: { duration: 7, resolution: "720p", aspectRatio: "9:16", generateAudio: true },
    subject: "네온으로 빛나는 도쿄 거리",
    action: "밤비가 내리며 젖은 아스팔트에 빛이 반사되는",
    setting: "도쿄 사이버펑크 거리, 빛나는 네온 웅덩이들",
    cameraShot: "tracking shot",
    lighting: "neon cyberpunk",
    mood: "mysterious",
    visualStyle: "cinematic realism",
  },
  {
    id: "space-walk",
    title: "우주 유영",
    description: "지구를 배경으로 우주를 유영하는 우주비행사",
    emoji: "🚀",
    prompt:
      "Astronaut floating in outer space with Earth in the background, wide shot, dramatic studio lighting, peaceful serene mood, cinematic realism, slowly rotating Earth, stars",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: false },
    subject: "우주비행사",
    action: "우주 공간에서 천천히 유영하는",
    setting: "별빛 가득한 우주, 지구가 배경으로 보이는",
    cameraShot: "wide shot",
    lighting: "studio lighting",
    mood: "peaceful serene",
    visualStyle: "cinematic realism",
  },
  {
    id: "beach-sunset",
    title: "해변 선셋",
    description: "황금빛 석양이 물드는 아름다운 해변",
    emoji: "🌅",
    prompt:
      "Golden sunset over ocean waves on a beautiful beach, wide shot, golden hour lighting, peaceful serene romantic mood, cinematic realism, camera slowly pushing toward the horizon",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "파도치는 아름다운 해변",
    action: "카메라가 수평선을 향해 천천히 전진하는",
    setting: "황금빛 석양이 물드는 바다",
    cameraShot: "wide shot",
    lighting: "golden hour",
    mood: "peaceful serene",
    visualStyle: "cinematic realism",
  },
  {
    id: "cyberpunk-chase",
    title: "사이버펑크 추격전",
    description: "미래 도시 밤거리의 긴장감 넘치는 자동차 추격전",
    emoji: "🏎️",
    prompt:
      "Futuristic cyberpunk city car chase at night, low angle tracking shot, neon cyberpunk lighting, tense dramatic intense mood, cinematic realism, rain-slicked streets, holographic billboards",
    settings: { duration: 10, resolution: "720p", aspectRatio: "21:9", generateAudio: true },
    subject: "미래형 자동차들",
    action: "비에 젖은 도로와 홀로그램 광고판 사이를 고속으로 질주하는",
    setting: "밤의 미래 사이버펑크 도시",
    cameraShot: "low angle shot",
    lighting: "neon cyberpunk",
    mood: "tense dramatic",
    visualStyle: "cinematic realism",
  },

  // ── 신규 8개 ─────────────────────────────────────────────────────────
  {
    id: "wizard-duel",
    title: "마법사 대결",
    description: "두 마법사의 화려한 주문 대결",
    emoji: "🧙",
    prompt:
      "Two powerful wizards in an epic magical duel, exchanging brilliant spell blasts, ancient castle interior with glowing magical energy, wide shot, dramatic shadows, epic action-packed mood, fantasy magical style",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "두 명의 마법사",
    action: "화려한 마법 주문을 주고받으며 격렬하게 대결하는",
    setting: "고대 마법 성 내부, 빛나는 마법 에너지가 가득한",
    cameraShot: "wide shot",
    lighting: "dramatic shadows",
    mood: "epic action-packed",
    visualStyle: "fantasy magical",
  },
  {
    id: "cat-office",
    title: "고양이 사무원",
    description: "작은 책상에서 진지하게 일하는 귀여운 고양이",
    emoji: "🐱",
    prompt:
      "Serious cat sitting at a tiny desk typing on a miniature keyboard, small cute office with adorable props, close-up shot, soft diffused lighting, playful whimsical mood, cinematic realism",
    settings: { duration: 5, resolution: "720p", aspectRatio: "1:1", generateAudio: false },
    subject: "아주 진지한 표정의 고양이",
    action: "작은 책상에서 키보드를 치며 열심히 일하는",
    setting: "미니어처 사무실, 귀여운 소품들로 가득",
    cameraShot: "close-up",
    lighting: "soft diffused",
    mood: "playful whimsical",
    visualStyle: "cinematic realism",
  },
  {
    id: "cherry-blossom",
    title: "벚꽃 만개",
    description: "봄 벚꽃이 슬로모션으로 활짝 피어나는 장면",
    emoji: "🌸",
    prompt:
      "Cherry blossom trees blooming in slow motion with petals floating in the breeze, Korean spring park with blossom tunnel path, dolly zoom, soft diffused lighting, romantic mood, cinematic realism",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "벚꽃 나무들",
    action: "꽃잎이 바람에 흩날리며 슬로모션으로 만개하는",
    setting: "한국 봄 공원, 벚꽃 터널 길",
    cameraShot: "dolly zoom",
    lighting: "soft diffused",
    mood: "romantic",
    visualStyle: "cinematic realism",
  },
  {
    id: "underwater-dive",
    title: "수중 탐험",
    description: "산호초 사이를 유영하는 스쿠버 다이버",
    emoji: "🤿",
    prompt:
      "Scuba diver swimming through vibrant coral reefs with tropical fish, beautiful underwater world with sunlight filtering through clear water, tracking shot, soft diffused lighting, peaceful serene mood, cinematic realism",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: false },
    subject: "스쿠버 다이버",
    action: "빛나는 열대어들과 함께 산호초 사이를 유영하는",
    setting: "아름다운 열대 산호초 수중 세계",
    cameraShot: "tracking shot",
    lighting: "soft diffused",
    mood: "peaceful serene",
    visualStyle: "cinematic realism",
  },
  {
    id: "piano-concert",
    title: "피아노 협주곡",
    description: "웅장한 콘서트홀에서 열정적으로 연주하는 피아니스트",
    emoji: "🎹",
    prompt:
      "Passionate pianist performing on a grand piano in a magnificent concert hall with thousands of audience and grand chandeliers, over-the-shoulder shot, cinematic lighting, tense dramatic mood, cinematic realism",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "피아니스트",
    action: "그랜드 피아노를 열정적으로 연주하는",
    setting: "웅장한 콘서트홀, 수천 관객과 화려한 샹들리에",
    cameraShot: "over-the-shoulder shot",
    lighting: "cinematic",
    mood: "tense dramatic",
    visualStyle: "cinematic realism",
  },
  {
    id: "ninja-night",
    title: "닌자의 밤",
    description: "달빛 아래 지붕 위를 달리는 그림자 닌자",
    emoji: "🥷",
    prompt:
      "Shadow ninja running and leaping between rooftops under full moonlight, ancient Japanese city at night, low angle shot, moonlight lighting, mysterious mood, anime style",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "그림자 닌자",
    action: "달빛을 받으며 지붕과 지붕 사이를 도약하며 달리는",
    setting: "고대 일본 도시, 보름달이 뜬 밤",
    cameraShot: "low angle shot",
    lighting: "moonlight",
    mood: "mysterious",
    visualStyle: "anime style",
  },
  {
    id: "dinosaur-era",
    title: "공룡 시대",
    description: "쥬라기 밀림을 걷는 거대한 티라노사우루스",
    emoji: "🦕",
    prompt:
      "Massive T-Rex roaring and walking majestically through dense Jurassic jungle, ancient tropical forest with giant fern plants, low angle shot, dramatic shadows, epic action-packed mood, cinematic realism",
    settings: { duration: 8, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "거대한 티라노사우루스",
    action: "울창한 쥬라기 밀림 속에서 포효하며 위엄있게 걷는",
    setting: "쥬라기 시대 열대 밀림, 거대한 고사리 식물들",
    cameraShot: "low angle shot",
    lighting: "dramatic shadows",
    mood: "epic action-packed",
    visualStyle: "cinematic realism",
  },
  {
    id: "robot-dance",
    title: "로봇 댄스",
    description: "미래 광장에서 화려한 댄스를 선보이는 로봇",
    emoji: "🤖",
    prompt:
      "Cute humanoid robot performing amazing smooth dance moves in a futuristic city plaza, neon lights and holograms everywhere, wide shot, neon cyberpunk lighting, playful whimsical mood, cinematic realism",
    settings: { duration: 7, resolution: "720p", aspectRatio: "16:9", generateAudio: true },
    subject: "귀여운 인간형 로봇",
    action: "화려하고 유연한 댄스 무브를 선보이는",
    setting: "네온 조명과 홀로그램이 가득한 미래 도시 광장",
    cameraShot: "wide shot",
    lighting: "neon cyberpunk",
    mood: "playful whimsical",
    visualStyle: "cinematic realism",
  },
];
